### ISSUE TITLE
Mirage2000 éjection handle missing

### ISSUE THREAD

**Issue by karl19170** [DCSFlightpanels/dcs-bios#106]
Bonjour
Il semble que le  code dcsbios pour déclencher l'éjection dans le mirage2000 pour Arduino est manquante

**Comment by WarLord211** [comment]
sorry no Frensh pls in english

**Comment by talbotmcinnis** [comment]
I believe he is stating that “It looks like the code to activate ejection in the mirage 2000 for Arduino is missing”.  “Activate” I’m not sure of though, that could also be referring to arming.  “Declench”.  English would certainly help :)

**Comment by karl19170** [comment]
Sorry
Yes the code to activate the ejection IS missing in the dcs bios
That what i meant
I'm bit Shy when it's Time to practice english due tonmy pour skills to
explain my mind
I Hope you understand better with this words
Best regards

**Comment by WarLord211** [comment]
hey 
english is also not my native so dont worry. learning by doing ;)
i did a quick look and cant find anny thing related the the ejection.
is it clickable? if not, it cant be integraded in BIOS.
What not mean it cant work with arduino
if clickable and PIC of the switch would help or a note were i can find it. (dont know the mirage well)
