### ISSUE TITLE
M-2000C `.json` and `.jsonp` files not generating

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#110]
M-2000C.json is currently blank
https://github.com/DCSFlightpanels/dcs-bios/blob/master/Scripts/DCS-BIOS/doc/json/M-2000C.json

When running dcs-bios, a blank file will be generated and then nothing will be generated for the .jsonp file, indicating to me that something is failing when trying to generate the json file.

**Comment by WarLord211** [comment]
Log File:
`Call error LuaExportAfterNextFrame:[string "C:\Users\*****\Saved Games\DCS\Scripts\DCS-BIOS\lib\M-2000C.lua"]:780: attempt to index a nil value
`
The part in the lua:
`defineIntegerFromGetter("RAD_VTB_RANGE", function() return parse_indication(1)["vtb-rdr-range"] end, 65535, "RADAR", "O - VTB Display Radar Range") `

**Comment by charliefoxtwo** [comment]
> Log File: `Call error LuaExportAfterNextFrame:[string "C:\Users\*****\Saved Games\DCS\Scripts\DCS-BIOS\lib\M-2000C.lua"]:780: attempt to index a nil value ` The part in the lua: `defineIntegerFromGetter("RAD_VTB_RANGE", function() return parse_indication(1)["vtb-rdr-range"] end, 65535, "RADAR", "O - VTB Display Radar Range") `

Worth noting what while this may be unrelated it might be worth opening a separate issue for this. I don't have the M-2000C so I can't test it personally.

Thanks for the fix on the json files though!
