### ISSUE TITLE
No Brightness Control in F-16.

### ISSUE THREAD

**Issue by Jacktherookie** [DCSFlightpanels/dcs-bios#113]
I'm trying to set flood light brightness according to position of the flood light knob.
But it seems flood light parts only emits 0 for off and 1 for on. Is there any options that I can control brightness of panel(or flood light itself)?
(By the way I'm using arduino not Flightpanel).

**Comment by WarLord211** [comment]
its not Flightpanel related more the BIOS Side.
i uploaded a "fix" they are not lights anymore thea are floats -> gives an % state
same as A-10 and FA-18
uploaded to master

**Comment by Jacktherookie** [comment]
> its not Flightpanel related more the BIOS Side. i uploaded a "fix" they are not lights anymore thea are floats -> gives an % state same as A-10 and FA-18 uploaded to master

Checking right now. I'll let you know when this works. Thanks.

**Comment by Jacktherookie** [comment]
> its not Flightpanel related more the BIOS Side. i uploaded a "fix" they are not lights anymore thea are floats -> gives an % state same as A-10 and FA-18 uploaded to master

Alright I just tested it - It's not working...

This is my Arduino Code

#define DCSBIOS_IRQ_SERIAL
#define flood_light 2

#include "DcsBios.h"

DcsBios::LED lightInstPnlFlood(0x4482, 0x0001, flood_light);

void setup() {
    pinMode(flood_light, OUTPUT);
  DcsBios::setup();
}

void loop() {
  DcsBios::loop();
}

As I adjust the knob, LED brightness itselft does not change according to its value. It's just blinking when I adjust it.



And this is what I recorded while testing. This video shows what's actually happening.

https://youtu.be/-3KYrClhHWU

**Comment by WarLord211** [comment]
the lights are not a "LED" anymore. the are "Servos" that gives you an % valve. 
(was user requests for F-18 and A-10 so i decided to go also for the F16)

the code must changed to DcsBios::IntegerBuffer with some additions. 
But how exactly that works i cant help you, since im more from the Plane as the arduino side.
if you come over to our discord there some folks which can help you. (link in readme)

**Comment by Jacktherookie** [comment]
> 

Thanks for reply. I already found that out like you said. Therefore I'm working out for it.

**Comment by Jacktherookie** [comment]
> the lights are not a "LED" anymore. the are "Servos" that gives you an % valve. (was user requests for F-18 and A-10 so i decided to go also for the F16)
> 
> the code must changed to DcsBios::IntegerBuffer with some additions. But how exactly that works i cant help you, since im more from the Plane as the arduino side. if you come over to our discord there some folks which can help you. (link in readme)

What's the range of the return value of Servo? isn't it from 0 to 65535?

**Comment by Jacktherookie** [comment]
Hi. I'm trying to make a flood light for F-16. But I found that original code for instrument panel flood light only emits 0 for off and 1 for on. So I made some inquiry to Warlord and he gave me some edit for F-16.lua files (https://github.com/DCSFlightpanels/dcs-bios/issues/113#ref-commit-3ea3d55). So after editing F-16.lua file,I started looking for some extra information.
My initial code for my flood light is

#define DCSBIOS_IRQ_SERIAL
#define flood_light 3

#include "DcsBios.h"

void onLightConslesFloodChange(unsigned int newValue) {
  int val255 = map(newValue, 0, 65535, 0, 255); // translate newValue(Trying to change 16 bit to 8 bit for PWM) into new integer variable called "val255"
  // int val255 = newValue * 255;
  analogWrite(flood_light, val255); //Light the LEDs.
}
DcsBios::IntegerBuffer lightConslesFloodBuffer(0x4480, 0x8000, 15, onLightConslesFloodChange);

void setup() {
  pinMode(flood_light, OUTPUT); //Pin 3 Output
  DcsBios::setup();
}

void loop() {
  DcsBios::loop();
}

But it seems not working for now. I'm trying to investigate further.

**Comment by talbotmcinnis** [comment]
I can’t confirm the dcs-bios side, but once you have the address/offset correct, you won’t need to much code on the arduino side.  The library already has a control that does what you want:

https://github.com/DCSFlightpanels/dcs-bios-arduino-library/wiki/Dimmer

**Comment by Jacktherookie** [comment]
> I can’t confirm the dcs-bios side, but once you have the address/offset correct, you won’t need to much code on the arduino side. The library already has a control that does what you want:
> 
> https://github.com/DCSFlightpanels/dcs-bios-arduino-library/wiki/Dimmer

Thanks for info. I've managed to work with Flood lights.

**Comment by WarLord211** [comment]
Top!
can the issue closed?
