### ISSUE TITLE
UH1H récupérer ADF et CAP

### ISSUE THREAD

**Issue by hugo28esca** [DCSFlightpanels/dcs-bios#116]
Bonjour,
j'ai réalisé un projet à partir de DCS bios et carte Arduino MEGA.
Tous les boutons fonctionnent.

J'ai également un écran LCD
je n'arrive pas a afficher l'ADF car il n'y a un code que pour la jauge. 
Quelle conversion faut-il appliquer?

idem pour le CAP, où trouver la référence? il y a t il une conversion à réaliser?

Merci pour votre retour

-----
Edit by Warlord via Google Translator:

Hello,
I made a project from the DCS bios and the Arduino MEGA board.
All buttons work.

I also have an LCD
I can't see the ADF because there is only one code for the counter.
Which conversion to apply?

ditto for the CAP, where can I find the reference? do you need to convert?

thank you for your opinion

**Comment by WarLord211** [comment]
Hi,
at first issues in english please. We have all different Languages and should use one everyone understands. 
i cant also not awnser in my language since nobody would understand it.

What is CAP? 
ADF freq is maybe possible as a string. have to look

**Comment by WarLord211** [comment]
ADF Readout as string not posible since the Valve shows the % the needle has moved on a dial that change his Valve/numbers/Freq.
i cant make a readout.

**Comment by WarLord211** [comment]
https://www.youtube.com/watch?v=DpYC2oEWer0
