### ISSUE TITLE
AH64D - PLT internal Light System - Pilot Master Caution Button - stopped working.

### ISSUE THREAD

**Issue by solexnl** [DCSFlightpanels/dcs-bios#117]
DcsBios::Switch2Pos pltIntlMcautionBtn("PLT_INTL_MCAUTION_BTN", 53);

This function has stopped working since the latest open beta update (24 agustus 2022)
Arduino Mega board.

Thank you very much :)

**Comment by WarLord211** [comment]
Latest master branch?
Addresses checked? (Maybe there changed, during updates from my side)
If you download latest master, remember to start a flight to automatic rewrite the jsons.
