### ISSUE TITLE
A10C - CDU_BRT Message have inverted Effect.

### ISSUE THREAD

**Issue by Cerppo** [DCSFlightpanels/dcs-bios#118]
Bright Rocket DIM /BRT animation is as Expected, but the effects are inverted 
=> Pressing BRT , dims the CDU , and vice versa.

**Comment by talbotmcinnis** [comment]
Testing A-10C II in DCS 2.7.17.29140 is working as expected.  Control ref set_state 2 holds right aka BRT. Value 0 holds left ie DIM.

If the poster really meant A-10C I not II then this MIGHT be a consequence of the recent cockpit changes that reordered some of the rotary directions?

**Comment by talbotmcinnis** [comment]
Oops.  Update: Can confirm exactly as described.  The animation of the button matches the commanded state, but the CDU display brightness is indeed opposite of the animation.

**Comment by WarLord211** [comment]
can i get the BIOS switch name of it?

**Comment by Cerppo** [comment]
Yes it's the A-10C/CDU_BRT

**Comment by WarLord211** [comment]
is easier for me if the BIOS name is included in an issue report.
i dont know all Planes and how things operate in them.
