### ISSUE TITLE
AH64-D UFD sends update string, while aircraft is Cold&Dark

### ISSUE THREAD

**Issue by Cerppo** [DCSFlightpanels/dcs-bios#119]
In a cold & Dark aircraft 

<img width="766" alt="image" src="https://user-images.githubusercontent.com/49897630/188264223-8747be51-18a2-4cb2-98f3-25c09f65d58e.png">

**Comment by WarLord211** [comment]
sorry can you descripe the problem a little more?
i dont understand the problem

**Comment by Cerppo** [comment]
it's strange that DCBios updates display when the aircraft is totally cold & dark ( not battery, no ac/power ?). In other aircrafts , A10C for ex, the CDU dont send line before the CDU is powered. 
You can see the UFD ( screen on the right part of the screenshot ) powered off and PLT_EUF_LINExx in the Live Ref view have received updated values with string and frequencies. 

hope that's clearer. 
Regards.

**Comment by WarLord211** [comment]
i dont kknow if we can do something. since BIOS get his data from the plane and if the plane send something without displaying it.
will have a look

**Comment by Cerppo** [comment]
possible workaround for me in my dcsfp plugin could be to get the "power state" and set my CDU bightness to 0 to it displays nothing when the aircraft is cold & dark ( sounds more logical too )

**Comment by WarLord211** [comment]
that would mean BIOS gets data from the plane before it is able to "generate" it, sounds also like an BUG from DCS side.

**Comment by charliefoxtwo** [comment]
Repro'd, investigating.

**Comment by charliefoxtwo** [comment]
I suspect the error is in the DCS AH-64D lua file `Cockpit\Scripts\Displays\EUFD\EUFD_Pages_Init.lua`. On line 47, it says:
```lua
init_pageID	= PAGE_MAIN
```

however I believe this should _instead_ be
```lua
init_pageID	= PAGE_BLANK
```

Changing the line as suggested does fix the issue. Seems like a bug with the DCS AH-64D luas and I'm not sure there's much we can do.

**Comment by WarLord211** [comment]
so its a ED/DCS BUG
