### ISSUE TITLE
F-16 DED problem after moving from v0.7.44 to v0.7.46

### ISSUE THREAD

**Issue by Maverick87Shaka** [DCSFlightpanels/dcs-bios#123]
Dear all,
After moving from v0.7.44 to v0.7.46 I have some strange characters at the and of lines of my DED ( not in each page, but 100% replicable in the LIST page for example, or in COM when selecting a specific line )
I have changed my Arduino code according to the new expression, and I have notice also that the string buffer is increased, from 25 to the actual 29. The change look like happens in the v0.7.45 that I've not used for my project.

``
#F-16 - add missing ECM lightEHSI fix; IFF Mode Fix; Temp KNB fix; Fix for https://github.com/DCSFlightpanels/dcs-bios/issues/89 (Fuel Quanty Test SW)
DED readout redone (brakes existing programms); Sorting fix for ECM items
``

What is the scope of the additional characters? What is the best way at this point to "truncate" them if it's not essential to replicate the DED?

Thanks

![DED_COM1](https://user-images.githubusercontent.com/51521/188604736-78fc6ead-9d0c-4474-b886-b7209f70126b.jpeg)
![DED_LIST](https://user-images.githubusercontent.com/51521/188604743-55938344-31ad-415b-aa5c-d719dc410407.jpeg)

**Comment by WarLord211** [comment]
chech the addresses, sadly due some changes they changed too, between the versions

**Comment by Maverick87Shaka** [comment]
> chech the addresses, sadly due some changes they changed too, between the versions

Yes I've changed the address according to the new version, and this one in the photo is the results that I have. 
Without changing the arduino code it was completely broken with some strange readout in all the lines.

**Comment by Maverick87Shaka** [comment]
According to the documentation after re-generating the files with version v0.7.46 the code should be:

``
void onDedLine1Change(char* newValue) {
    /* your code here */
}
DcsBios::StringBuffer<29> dedLine1Buffer(0x450a, onDedLine1Change);
``

I've changed the stringbuffer size back to **25** ( that is the value on the old v0.7.44 ) keeping the new address and it's working as expected.
Can you check if it's an error or not?  Not sure why control reference is now saying **29**

**Comment by fdallera** [comment]
The old DED solution doesn't take care of the reversed char, this it was implemented adding 4 bytes for each line that it is the bitmap of reversed chars.
for to simplify the loop bit 0 is related to Byte 0 and so on (take care that the display row array is starting from the left to the right and a bitmap is starting from the right to the left) 

This is the best way i found to add the handling of reversed char without to manage it from Arduino side that it was a nightmare specially for edit and blinking field.
The solution it adda only 4 bytes … that if you are not interested to handle you can cut
(BMS solution it send twice the displayed area normal and reversed)

**Comment by Maverick87Shaka** [comment]
Thanks @fdallera
Now it makes sense ( so it's not an issues anymore if u want close @ WarLord211 ). Personally I didn't feel the lack of the reverse character, even if in some page like LIST can look ugly.
But since there is the option, I would like to try it.
there is any other documentation available on how to use it or some example code maybe?

**Comment by fdallera** [comment]
This is the code of course is related to my fonts



void setupContent(char * dedRec, int row) {
  
  unsigned long bitMap;
  memcpy(&bitMap,   &dedRec[DISP_SIZE], 4 );
  dedString[row] = String(dedRec).substring(0, 24);

  dedString[row].replace(0x6F, 0x5E);     // Change char '&' (111) in reverse witn '°' (94) in ASCII (in my fonts)
  for (int i = 0; i < DISP_SIZE; i++)  {
    if(bitRead(bitMap, i)) {
      dedString[row].setCharAt(i, dedString[row].charAt(i) + INV_FONT);
    }
  }
}

**Comment by emcek** [comment]
@Maverick87Shaka side question... what font you are using for DED? I get problem with `up and down` arrow/triangle character.

**Comment by Maverick87Shaka** [comment]
> @Maverick87Shaka side question... what font you are using for DED? I get problem with `up and down` arrow/triangle character.

I'm using U8G2 library with custom font

**Comment by emcek** [comment]
> I'm using U8G2 library with custom font
Are you able to share this font?

**Comment by fdallera** [comment]
> 

it is not only a matter of "feeling", reverse is used to highlight also input field, blinking is used for wrong input

**Comment by fdallera** [comment]
Same, I'm using U8G2 with custom FONTS (attached)
Beware this is NOT a standard ASCII font... alphabetic characters are the same as ASCII but some symbols are not (this means you need to check and convert it)
This is because I put REVERSED Char at a specific offset, so it's easier to change the standard char to reverse
Reverse font = standard font + 73 (in my font)

It is not recommended to use U8G2 inverse graphing function because it is resource intensive (ram and time) and therefore you need to work in x,y coordinates instead of row and column... but that's up to you

[Fonts.zip](https://github.com/DCSFlightpanels/dcs-bios/files/10555879/Fonts.zip)
