### ISSUE TITLE
Mi-24P: switches of FIRE PROTECTION SYSTEM

### ISSUE THREAD

**Issue by Saylors** [DCSFlightpanels/dcs-bios#124]
1. Switch "PILOT Extinguisher Power ON/OFF" works only in position 1, in position 2 does not work.
2. The "PILOT Fire Extinguisher Sensor Channel OFF/1/2/3" switch only works in one of the three positions.
Using DCS-BIOS_0.7.46 and DCSFlightpanels_x64_4.6.8285.2 .
![Screen_220917_210458+](https://user-images.githubusercontent.com/50142231/190873530-c3f0deb5-9ba2-4ee4-875f-b1fa6a5abaaa.png)
![Screen_220917_210502+](https://user-images.githubusercontent.com/50142231/190873532-f3896609-1695-42af-9161-f1d075d765e0.png)

**Comment by WarLord211** [comment]
perfect report!!!
And it should fixed pls test.
(uploaded to master, start a flight before testing to rewrite json data)

**Comment by Saylors** [comment]
It worked perfectly now! Thank you so much!
PS: I try to make reports understandable.
