### ISSUE TITLE
Mi-24P: SARPP-12 not on the menu.

### ISSUE THREAD

**Issue by Saylors** [DCSFlightpanels/dcs-bios#125]
The SARPP-12 switch is not on the menu or list.
![Screen_220919_174636](https://user-images.githubusercontent.com/50142231/191534977-b14f284a-c7b7-420e-9215-d14457be555d.png)

**Comment by WarLord211** [comment]
Uploaded to master
Pls try.

**Comment by Saylors** [comment]
Thanks, it's working!21.09.2022, 22:40, "Sven" ***@***.***>:
Uploaded to master
Pls try.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
Best regards, Vyacheslav

**Comment by Saylors** [comment]
> Uploaded to master Pls try.

Thanks, it's working!
