### ISSUE TITLE
AAP_STEER in A-10C not working as coded

### ISSUE THREAD

**Issue by ColdFrontWI** [DCSFlightpanels/dcs-bios#128]
I had almost every control in my A-10C pit working...the one exception was the steerpoint toggle on the AAP ("AAP_STEER" message).  The original code in A-10C.lua is as follows:
`defineRockerSwitch("AAP_STEER", 22, 3003, 3003, 3002, 3002, 474, "AAP", "Toggle Steerpoint")`

Changing it to a "spring-loaded 3-position tumbler" works.  (I based the code on the seat adjust code.)  The new line in A-10C.lua is:
`defineSpringloaded_3PosTumb("AAP_STEER", 22, 3003, 3002, 474, "AAP", "Toggle Steerpoint")`

This works in both the A-10C II and the base A-10C.

Thanks,
Eric

**Comment by WarLord211** [comment]
Thanks for the fix. is uploaded to master
