### ISSUE TITLE
DCS_BIOS no longer supported in Chrome

### ISSUE THREAD

**Issue by Ben-F111** [DCSFlightpanels/dcs-bios#132]
On re installing control references in Chrome extensions, I get the below warning

![image](https://user-images.githubusercontent.com/67782885/202797400-1d389b99-ff84-4de4-a052-6b712fd5e6da.png)

**Comment by DeadMeatDCS** [comment]
charliefoxtwo has made Bort which is working great as a replacement.

Get it here: https://github.com/charliefoxtwo/Bort
