### ISSUE TITLE
AH-64D Both Pilot and Gunner Signal Light (color) is 0-1 should be 0-65535

### ISSUE THREAD

**Issue by flanker0ne** [DCSFlightpanels/dcs-bios#135]
![knob](https://user-images.githubusercontent.com/105388387/209423165-6f5a77f6-5698-4098-87ac-4042d3bdae8b.JPG)
![Code](https://user-images.githubusercontent.com/105388387/209423168-39c8c58a-091d-499d-9192-f9cecf943fab.JPG)

**Comment by WarLord211** [comment]
Pls test

**Comment by flanker0ne** [comment]
Hi, I've make some test and the read from the potentiometer are now in the range supposed to be, thanks ;-)

But unfortunately I've noticed another issue with the PRIMARY potentiometer.

![Primary Panel Lighting 50%](https://user-images.githubusercontent.com/105388387/209479959-e8d661aa-1cf1-44c2-9caa-6fcfa6d59c9f.JPG)
At 50% of it's excursion, the output is around 10%....
![Primary Panel Lighting 100%](https://user-images.githubusercontent.com/105388387/209479962-3ce71384-3f15-4304-ac8a-1a1c3c2672da.JPG)
... while at 100% is 90%. It cant reach 65535

**Comment by WarLord211** [comment]
the problem is that these vales were nowhere in the code, they were guessed from the model itself.
since i dont know the apache, i programmed as i guessed and need feedback from users ;)

**Comment by WarLord211** [comment]
can you give me the name oft the Poti? the Panel lighting readout from your screenshot is only the light intensity.

**Comment by flanker0ne** [comment]
Yes I can only try to figure out the problem. The complexity of your work grow with the number of module and with the complexity of that particular module.
I'm gratefull and happy to making a little part in your effort

**Comment by flanker0ne** [comment]
> can you give me the name oft the Poti? the Panel lighting readout from your screenshot is only the light intensity.

Pilot Primary Lights Control Knob

Remember the CPG cockpit have those controls as well =b

**Comment by WarLord211** [comment]
i checked the code. BIOS works with the Model Arguments and these 2 are linear in the Cockpit Model. booth work from 0 to 1. so something in the code must be strange. Needs more investigation. since to late for today i look into it when i have more time

**Comment by flanker0ne** [comment]
Take your time, and happy holydays

**Comment by DeadMeatDCS** [comment]
@flanker0ne Looks like this is a quirk of the module itself in DCS. The panel light (primary lights) knob models a logarithmic potentiometer (well rheostat probably) in that you gotta turn past 50% to get to just 10% intensity and then it takes off towards the end. I have not seen this modeled in any other module in this way.

The cockpit animation goes all the way from 0-100% in the model itself but this is not reachable in the sim as you point out. This may be similar to the pressure setting counter on the F18 that had part of the range outside of user reach. Strange way to implement it - perhaps a bug in DCS, but not really in DCS-BIOS I'd say.

_If you want linear output for your LEDs you could:_
A) Base LED output on the knob position which is 0-100% linear. You could check that light intensity output is >0 for when to allow the LEDs to turn on in the first place to ensure they only come on when you have power on the bus.
B) Remap the light intensity output from DCS-BIOS in several steps to approximate a linear output.

**Comment by flanker0ne** [comment]
Hi guys, thanks for your attention
