### ISSUE TITLE
F-14: PLT_AUTOPLT_ENGAGE switch not defined correctly

### ISSUE THREAD

**Issue by parkerfly5150** [DCSFlightpanels/dcs-bios#136]
The PLT_AUTOPLT_ENGAGE entry in the F-14.lua file is configured as "defineFixedStepTumb" instead of "defineToggleSwitch".  The actual switch is a two-position switch.  I've been changing it manually successfully for awhile now but hoped it could be changed permanently in the builds.  

Full incorrect entry...
defineFixedStepTumb("PLT_AUTOPLT_ENGAGE", 22, 3040, 2112, 2, {-1, 1}, {-1, 1}, nil, "Autopilot", "PILOT Autopilot - Engage")

Full working entry...
defineToggleSwitch("PLT_AUTOPLT_ENGAGE", 22, 3040, 2112, "Autopilot", "PILOT Autopilot - Engage")

Thank you!

**Comment by WarLord211** [comment]
no this change was made because with a toggle switch when you disengage it the others didnt auto switch back

**Comment by parkerfly5150** [comment]
Interesting... thanks for the explanation!  I'll continue doing what I've been.
