### ISSUE TITLE
F/A18-C Stand By Altimeter 1000 Feet Count

### ISSUE THREAD

**Issue by Lot2Learn2** [DCSFlightpanels/dcs-bios#137]
Hi, 
First thanks to everyone who maintains this indispensable add-on to DCS.

In the process of building a stand by altimeter for my cockpit, I've noticed that there is a bug on the thousand feet count, When starting an instant action like in free flight where the plane starts at +/- 8000 feet there is no data in the control reference at the 1000 count. I descended to under 1000 to find out that it worked ok between 50 and 1000 feet like if it was counting the hundreds instead of the thousands.

Climbing back to over a thousand it freezes again, it comes back working ok between ( 10 000 and 11 000) than freezes again, and it goes on at 20 000, 30 000 and 40 000.

Thanks for having a look at this

Reg
![Screenshot 2023-01-05 205606](https://user-images.githubusercontent.com/122068962/210923891-39c1bb5b-0cd5-4359-a9a2-fb38669a66e4.jpg)
![Screenshot 2023-01-05 210042](https://user-images.githubusercontent.com/122068962/210923893-58720c07-d906-40ce-b224-578d647dd73f.jpg)

**Comment by WarLord211** [comment]
you use FP or HUB?

**Comment by Lot2Learn2** [comment]
I use FP, thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by DeadMeatDCS** [comment]
@Lot2Learn2 yep it's bugged. Hundreds counter on the pressure setting is suffering the same problem.
I've submitted a pull request with a fix for both. You can apply it yourself until it get's merged.

Change lines 891 and 894 in the FA-18C_hornet.lua to
defineFloat("STBY_ALT_1000_FT_CNT", 219, {0, 1}, "Standby Altimeter", "1000 ft count")
defineFloat("STBY_PRESS_SET_2", 223, {0, 1}, "Standby Altimeter", "Pressure Setting 3")

**Comment by WarLord211** [comment]
Thanks for the fix is merged!
@Lot2Learn2 if good pls close the issue

**Comment by Lot2Learn2** [comment]
Thanks Everyone,  Altimeter now works fine in DCS Bios FP and on my digital Gauge. Work now continues for me trying to get the Arduino sketch to work with the Baro.

Very Impressed, this situation was solved in less than 24 hours.

I'm very grateful you guys took the time so quickly to help me out.
