### ISSUE TITLE
Reference Library is not working

### ISSUE THREAD

**Issue by Jacktherookie** [DCSFlightpanels/dcs-bios#140]
Arduino Reference library is not working anymore since latest chrome update. I guess. Is there any workaround to avoid this?

**Comment by Maverick87Shaka** [comment]
use old version of chrome or try to use Bort or similar project ( https://github.com/charliefoxtwo/Bort/releases )

**Comment by Jacktherookie** [comment]
> use old version of chrome or try to use Bort or similar project ( https://github.com/charliefoxtwo/Bort/releases )

Thanks :)
