### ISSUE TITLE
A10C inverter switch not going to TEST position

### ISSUE THREAD

**Issue by No1sonuk** [DCSFlightpanels/dcs-bios#141]
The inverter switch on the A10C electrical panel is not going to the TEST position.  OFF and STBY work fine.
Code line:
DcsBios::Switch3Pos eppInverter("EPP_INVERTER", PIN_A, PIN_B);

**Comment by WarLord211** [comment]
Via Refpage/bort i can switch to all 3 states.
![2023-01-29 (1)](https://user-images.githubusercontent.com/10798954/215314921-352dc692-c41b-4f89-b58a-ed9cb3ed9e40.png)
![2023-01-29 (2)](https://user-images.githubusercontent.com/10798954/215314923-6918c58c-a9d5-45e2-b310-64ec7a440357.png)
![2023-01-29](https://user-images.githubusercontent.com/10798954/215314925-d6c0094c-f989-4cce-8213-f12be5870740.png)

**Comment by No1sonuk** [comment]
Odd.  Looks like I tried an old version yesterday.
Fresh install on new machine today, and it's working properly.
Thanks for your time, and sorry for wasting it.
