### ISSUE TITLE
AH-64D Fire Extinguisher Lights, need to be updated due to DCS modification

### ISSUE THREAD

**Issue by flanker0ne** [DCSFlightpanels/dcs-bios#145]
All the Fire Extinguisher Lights not mirror what happen in cockpit, while they lit all toghether if the Reserve Discharge (lower-right) is turned ON.

**Comment by WarLord211** [comment]
Need more info. i dont know the Apache.
i would need the names of the LIghts in BIOS ( like PLT_APU_READY_L)
what is the problem

**Comment by flanker0ne** [comment]
AH-64D/PLT_ENG_1_FIRE_L
AH-64D/PLT_ENG_1_READY_L
AH-64D/PLT_APU_FIRE_L
AH-64D/PLT_APU_READY_L
AH-64D/PLT_ENG_2_FIRE_L
AH-64D/PLT_ENG_2_READY_L
AH-64D/PLT_FIRE_EXT_DISCH_PRI_L
AH-64D/PLT_FIRE_EXT_DISCH_RES_L

Probably for CPG too
AH-64D/CPG_ENG_1_FIRE_L
AH-64D/CPG_ENG_1_READY_L
AH-64D/CPG_APU_FIRE_L
AH-64D/CPG_APU_READY_L
AH-64D/CPG_ENG_2_FIRE_L
AH-64D/CPG_ENG_2_READY_L
AH-64D/CPG_FIRE_EXT_DISCH_PRI_L
AH-64D/CPG_FIRE_EXT_DISCH_RES_L

**Comment by WarLord211** [comment]
can it closed?

**Comment by flanker0ne** [comment]
Yes, my fault
Lot of noise on the shift reg
