### ISSUE TITLE
Empty lines in F-16's DED

### ISSUE THREAD

**Issue by emcek** [DCSFlightpanels/dcs-bios#146]
I found 3 cases where DED line has no value:
# List 1 - T-ILS
![list_1_tils](https://user-images.githubusercontent.com/475312/216726901-d665092e-0ab6-47d9-b615-80ff55d1a08d.jpg)
```
DEBUG   | F16C50 DED_LINE_1 : "  UTM DEST * 21*a        "
DEBUG   | F16C50 DED_LINE_2 : "      GRID  31N   CNVRT  "
DEBUG   | F16C50 DED_LINE_3 : "    SQUARE  AA      0FT  "
DEBUG   | F16C50 DED_LINE_4 : "EAST/NORTH  66021/00000  "
DEBUG   | F16C50 DED_LINE_5 : "                         "
```

# List 3 - VIP:
![list_3_vip](https://user-images.githubusercontent.com/475312/216726915-62691d29-6742-491a-a326-b1edaf4d7e28.jpg)
```
DEBUG   | F16C50 DED_LINE_1 : "     *VIP-TO-TGT*         "
DEBUG   | F16C50 DED_LINE_2 : "     VIP    1 a          "
DEBUG   | F16C50 DED_LINE_3 : "    TBRG    0.0o         "
DEBUG   | F16C50 DED_LINE_4 : "                         "
DEBUG   | F16C50 DED_LINE_5 : "    ELEV       0FT       "
```

# List 9 - VRP:
![list_9_vrp](https://user-images.githubusercontent.com/475312/216726923-c3c2af59-e7df-4d9c-837f-f863c2ed8392.jpg)
```
DEBUG   | F16C50 DED_LINE_1 : "     *TGT-TO-VRP*         "
DEBUG   | F16C50 DED_LINE_2 : "     TGT    1 a          "
DEBUG   | F16C50 DED_LINE_3 : "    TBRG    0.0o         "
DEBUG   | F16C50 DED_LINE_4 : "                         "
DEBUG   | F16C50 DED_LINE_5 : "    ELEV       0FT       "
```

**Comment by fdallera** [comment]
iI'll check , which is your DCS-BIOS Version?

**Comment by emcek** [comment]
> iI'll check , which is your DCS-BIOS Version?
0.7.47

**Comment by fdallera** [comment]
i'm sorry but i tested all the three pages and as you can see from the attached images are all OK, it look like you are using a wrong version of DCS-BIOS  PC Script the last F-16C_50.lua script is V1.15 
Frow where did you get this DEBUG? 
Take care that a lot of DCS DED data from DCS they are extracted with the same ID like RANGE data ELEVETION data and so on,but different contest, some of them can share the same row and column some of them no but this is something that F-16C_50.lua is handling correctly
![VRP](https://user-images.githubusercontent.com/18698792/216783451-a152b9c2-2b11-4c87-af85-7eee35189429.jpg)
![DEST](https://user-images.githubusercontent.com/18698792/216783454-d3563491-9639-4075-8872-a7f1f7badda7.jpg)
![VIP](https://user-images.githubusercontent.com/18698792/216783456-53b3f2ca-63b5-4ece-866d-5b5b645c3a96.jpg)

**Comment by WarLord211** [comment]
@emcek  x.x47 is the latest release version. if you play DCS in Beta you should use master branch if bios there are the latest updates and fixes integraded.

**Comment by emcek** [comment]
Let me check `master` then

> it look like you are using a wrong version of DCS-BIOS PC Script the last F-16C_50.lua script is V1.15

Strangely I got V1.15 by WarLord (form official 0.7.47 release)
 
> Frow where did you get this DEBUG?

This is my python script/application which use UDP socket to extract data form DCS-BIOS


Anyway I will try use `master` and check, how it works.

**Comment by emcek** [comment]
Ok I use `master` version 16c5061694c05226b0ce87f2804b0d817855f407
But still got problem. I use [jboecker's parser](https://github.com/jboecker/python-dcs-bios-example) to export DCS-BIOS data stream.
1.Take a look at **T-ILS** I move cursor to 4th line:
![dcs_ded1](https://user-images.githubusercontent.com/475312/216849517-251a2e62-5262-4594-aede-51fe1450fc0d.jpg)
but from DCS-BIOS I got something like this (missing 5th line):
![ded1](https://user-images.githubusercontent.com/475312/216849594-a6e744ee-e446-4a74-b0c4-fb2d139e372e.jpg)
2. Then I move cursor to 5th line:
![dcs_ded2](https://user-images.githubusercontent.com/475312/216849651-c02d17e7-b4a3-46e4-88d2-e4125709e55c.jpg)
and at my end I got (part of 5th line appear at 3rd line!):
![ded2](https://user-images.githubusercontent.com/475312/216849671-45b3a3fc-ec7a-48bf-8781-7ab6868fcf80.jpg)
3. But i.e. here text **ELEV 0FT** appear correctly
![dcs_ded3](https://user-images.githubusercontent.com/475312/216849748-ba7057c2-0b5b-4ae0-82a2-ab7d8a47821d.jpg)
![ded3](https://user-images.githubusercontent.com/475312/216849756-9a1f1269-da9e-46ca-8dc3-3c95b8ca202e.jpg)
4. And still problem with:
![dcs_ded4](https://user-images.githubusercontent.com/475312/216850152-1eb4a006-1921-4330-9c06-14efb90255b5.jpg)
![ded4](https://user-images.githubusercontent.com/475312/216849863-ef9039b6-05b1-4cde-9ed8-b8c55a7baba0.jpg)
and
![dcs_ded5](https://user-images.githubusercontent.com/475312/216849872-0f7624fa-42f6-431c-996a-96af14f60f6a.jpg)
![ded5](https://user-images.githubusercontent.com/475312/216849875-b272a846-94a9-4826-9c29-f0ba5168a891.jpg)

I use jboecker's parser with UDP multicast socket to fetch DED data as (based on `F-16C_50.json`):
```
{'DED_LINE_1': {'address': 17674, 'max_length': 29}}
{'DED_LINE_2': {'address': 17704, 'max_length': 29}}
{'DED_LINE_3': {'address': 17734, 'max_length': 29}}
{'DED_LINE_4': {'address': 17764, 'max_length': 29}}
{'DED_LINE_5': {'address': 17794, 'max_length': 29}}
```
I do not claim it is DCS-BIOS bug but it is really strange, but I do not see any misbehavior at my end (my python script)

**Comment by fdallera** [comment]
On my DED i display exactly what i receive from  DCS-BIOS Socat that it is exaclty what it is sent from DCS-BIOS and prepared from F-16_C50.lua ... this it means that from a DED (arduino) side I don't have to do any processing other than display the rows (and reverse the contents that need to be reversed) and my DED can be considered a reliable debugging tool, no arduino changes can be done if new pages are added or something is changed inside them (except for the ADDRESS) 
So if i my DED is displayed correctly it means that it is correctly send from DCS-BIOS

  i don't know jboecker's parser example and python but if is substitute F-16_C50.lua i can guess this is wrong...
I implemented F-16_C50.lua to handle reverse field and to insert new pages and i didn't care/know the process after the buildDEDLine function but i'm sure that this line are correctly build. 
What i understood from my developments (empiric/debugging ) is that:
- DCS-BIOS doesn't send ALL the display but only the changed rows, this is why it is displayed when you "touch" 5th line
- Fields like RANGE and ELEVATION from DCS are common in different pages but sometimes with different rows and columns this is why in DED lines table in F-16_C50.lua the Page/row/field ID is changed from the DCS ID in PAGE_ID i mean something like form 'Range' in 'TGT-TO-VRP Range' for to get the right column and row from the DED table... 
for examples in your first screenshot for UTM DEST is changed from "ELEV" to "UTM DEST ELEV"
This misunderstanding cna gave the effect that you reported - to show the data on a wrong line - but is correctly handled in F-16_C50.lua (for the managed pages) 
Your beahavior could be justified only if F-19_C50.lua is NOT used or a wrong or very old or bugged version of F-16_C50.lua is used.

Are you using more then one DCS intallation? do you have different Saved Games directory? 
try to use this lua instead of F-16_C50.lua and then check what is wrote in DCS-BIOS.log but take care that every DCS-BIOS cicle is wrote and it can create a big big log 
here you can check what it is prepared for the SEND routine for each line BUT as i wrote above the SEND routine then it send ONLY the changed ROWS because the cicle is related to the DCS-BIOS polling on DCS data NOT on a kind of interrupt for data changed 
this is for to optimize the network amount of data sent 

of course you have to rename the file ..... 
[F-16C_50.DEBUG.lua.zip](https://github.com/DCSFlightpanels/dcs-bios/files/10663039/F-16C_50.DEBUG.lua.zip)

**Comment by emcek** [comment]
btw. **jboecker's parser** it is simple DCS-BIOS parser, I can subscribe for ADDRESS (`length`, `mask`, `shiftby` values) and if BIOS send changed value at this ADDRESS parser fire callback set by me.

So, I'm not sure what is a roll of `F-16_C50.lua` how it is involve in sending/modifying values send via DCS-BIOS protocol. To be clear I listen only on [UDP multicast] socket(https://github.com/DCSFlightpanels/dcs-bios/blob/master/Scripts/DCS-BIOS/doc/developerguide.adoc#connecting-to-dcs-bios) of DCS-BIOS.

My original idea of misbehave at my side was that for some reason value of DED_LINE_* was not change so it wasn't send by DCS-BIOS. I can observe this when I `Ecs` form cockpit (then my script update with general information version, clock etc. not DCS related stuff) when I back to cockpit, I do not see any DED info unless some data will be change.

I have one OB installation and one Save Games directory.

I will try debug version of `F-16_C50.lua` and back to you.

**Comment by emcek** [comment]
@fdallera I got some udpate

1. I clean `Saved Games\DCS.openbeta\Logs`
2. run with debug version as quick I could to decrease log file size. 
3. I fire instant action with Viper: switch `T-ILS`, `VIP-TO-TGT` and `TGT-TO-VRP`
4. exit the mission.

i.e. with `VIP-TO-TGT` I see RNG line/value is fetch and updated:
```
F-16C_50.lua: label: Range<-------- Loop
F-16C_50.lua:     k: Range
F-16C_50.lua:     v: RNG
:
F-16C_50.lua: label: Range value<-------- Loop
F-16C_50.lua:     k: Range value
F-16C_50.lua:     v:  0.0
:
F-16C_50.lua: label: Range NM<-------- Loop
F-16C_50.lua:     k: Range NM
F-16C_50.lua:     v: NM
:
F-16C_50.lua: DED_fields: { 
				["Range NM"] = NM,
				["Elevation value"] =      0FT,
				["VIP number value"] =   1,
				["Range"] = RNG,
				["Elevation value_placeholder"] = ,
				["Visual initial point to TGT Label_placeholder"] = ,
				["Visual initial point number"] = VIP,
				["VIP number up down arrows"] = a,
				["VIP to TGT Label Asteriscs_lhs"] = *,
				["Range value_placeholder"] = ,
				["VIP bearing value"] =   0.0o,
				["Elevation"] = ELEV,
				["VIP number value_placeholder"] = ,
				["Range value"] =  0.0,
				["VIP bearing value_placeholder"] = ,
				["Visual initial point to TGT Label"] = VIP-TO-TGT,
				["VIP to TGT Label Asteriscs_rhs"] = *,
				["VIP bearing"] = TBRG,
				l}
```
but final result is:
![image](https://user-images.githubusercontent.com/475312/218308299-6a6bce3b-370a-4b4f-bd2e-0427d4344c30.png)
Zipped log file: [DCS-BIOS_log.zip](https://github.com/DCSFlightpanels/dcs-bios/files/10715940/DCS-BIOS_log.zip)

**Comment by emcek** [comment]
If I grep log file for: `F-16C_50.lua: dataLine OUT 4 - len(29) :` I got 514 entries only with those lines:
![image](https://user-images.githubusercontent.com/475312/218309266-0decc6e8-6080-4668-ba28-a24aa276e0dc.png)

**Comment by fdallera** [comment]
i don't know what to say now... 
It look like ROW 4 is skippedbut this it doesn't happen on my PC
in your LOG this debug message is missed
![immagine](https://user-images.githubusercontent.com/18698792/218327479-fb419bf5-4774-400d-9766-524c525ce70e.png)
and of course this it change the final result 
![immagine](https://user-images.githubusercontent.com/18698792/218327586-6e0d4bc6-6e4c-4260-a82f-f7569fb7a431.png)
this one
It look like if it get an error betwin row3 and 5... check if it is reported in DCS.LOG

then ... the DEBUG that i send you it is related to 1.14 version but it doesn't matter for your test the difference is that HTS/HARM and STPT to MGRS pages are not handled
this is the last one 
[F-16C_50.DEBUG.lua.zip](https://github.com/DCSFlightpanels/dcs-bios/files/10716804/F-16C_50.DEBUG.lua.zip)

as i told you i have two installation of DCS and DCS-BIOS one that i use for develop and test and another clean installation that i use to flight with my group nad in both it is working fine i can suggest you what DCS peaople suggest in this cases CLEAN all your installation with a deep REPAIR DON't Install
 any MOD or external applications (except DCS-BIOS of course) and the run the test again

**Comment by emcek** [comment]
Ok I got culprit! But let me write what I done:
* Clean up `Saved Games\DCS.openbeta\Mods`
* Clean up `Saved Games\DCS.openbeta\Scripts`
* Keep only DCS-BIOS in `DCS.openbeta\Scripts\Export.lua`
* Repair (long) and clean DCS World installation

After that with `F-16C_50.DEBUG.lua` and `master` version DED works correctly. After a bit testing, culprit is:
* [pw-dev_script](https://github.com/pet333r/pw-dev_script) (is kind of same purpose like DCS-BIOS as far I know) which is needed for [DCS UFC](https://play.google.com/store/apps/details?id=com.dcsufc)

Rest of modes and scripts in do not matter, they working nicely with DCS-BIOS and DED (in may case).

Scripts:
* DCS-BIOS
* VAICOMPRO
* SimShaker
* Tacview
* DCS-SRS

I think it is end of troubleshooting, this is sad I need choose between DCS-BIOS or pw-dev_script and DCS UFC, but... life sucks ;)

IMHO you can close this issues if you would like to... thx for time and effort, this is nice we got to the root cause!

**Comment by fdallera** [comment]
why choose between DCS-BIOS  and pw-dev_script, given that I don't know pw-dev_script  but it look like a pw-dev_script bug or conflict and you can open a issue in PW-DEV_Script they give full compatibility with DCS-BIOS.
They do the same things ... in casws like this i have experience only with HELIOS and DCS-BIOS togheter without any conflict
