### ISSUE TITLE
A-10C `VHFAM_FREQ1` out of range

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#150]
The logs are flooded with this:
```
Util.lua: value -3.000000 is too small for address 4494 mask 15
```
This is the `VHFAM_FREQ1`. I don't know anything about the control or why the value is negative, but perhaps it has something to do with the ARC-210 and the old radios not existing anymore?

**Comment by WarLord211** [comment]
its came from the older generic implementation of the Arc.
Newer one is uploaded

**Comment by WarLord211** [comment]
these error occur from all modules sometime, dont know were they came from since these valves not possibe for these switches.
since the didnt stop bios, i ignore them the last years.

**Comment by WarLord211** [comment]
with the old radios maybe something can be done like:

if a-10C then old radios
if a-10C2 the new radios

**Comment by charliefoxtwo** [comment]
This one is stopping bios for me. Unless I comment this line out, bios does not work in the A-10C II for me.

**Comment by WarLord211** [comment]
this line doesnt exist in the latest lua. was a placeholder before arc goes final/beta.
