### ISSUE TITLE
Implement LuaExportStart() function

### ISSUE THREAD

**Issue by srobert72** [DCSFlightpanels/dcs-bios#153]
Hello,
Thank you for your great work !
Is it possible to implement **LuaExportStart()** function and send UDP Metadata informations (like ACFT_NAME, DCS_BIOS version and PILOTNAME) before the user click on fly button (when the user is the briefing screen) ?

Thank you in advance
Regards

**Comment by charliefoxtwo** [comment]
Do you have documentation for this? I'm not too familiar with what dcs is looking for but documentation on what this does, what it expects, etc would be helpful

**Comment by srobert72** [comment]
In fact DCSBios already implements this :

```
function LuaExportStart()
...
end
```
But it doesn't send nothing over UDP.
To receive the first UDP messsage, we must wait for the first execution of this :
```
function LuaExportBeforeNextFrame()
...
end
```
In order to prepare a player session I'd like to receive some basic informations during **LuaExportStart()**.
I think it's good be simple, just send same informations but for the first time in another function call.
ACFT_NAME, DCS_BIOS version and PILOTNAME don't need a flight in progress to be known.

**Comment by WarLord211** [comment]
Have you the knowledge for that?

**Comment by charliefoxtwo** [comment]
@srobert72  `ACFT_NAME` and `PILOTNAME` do need you to select a role though right? because in multiplayer you can choose any role and you can get to the briefing screen without choosing a role as well.

Separately, I know bios doesn't export at all when the mission is paused, so it might be we don't have control over what happens at that time?

**Comment by charliefoxtwo** [comment]
Ok so I experimented with sending data during export start, and the aircraft name was not sent.

The difficulty here is `LuaExportStart()` is run when the mission is loading, and before the briefing screen is ever seen. As such, I suspect this information simply isn't available at this time and there's nothing we can do here unfortunately.

Unless anyone has any information to the contrary, @WarLord211 I'd suggest closing this as something we simply aren't able to do.
