### ISSUE TITLE
MosquitoFBMkVI: Bomb Doors Lever doesn't work.

### ISSUE THREAD

**Issue by Saylors** [DCSFlightpanels/dcs-bios#156]
1. The "Bomb Doors Lever" in positions 1 and 2 only switches down - the up and neutral positions do not work.
    Using DCS-BIOS_0.7.47 (Update https://github.com/DCSFlightpanels/dcs-bios) and DCSFlightpanels_x64_4.6.8444.4 .
![Screen_230324_001917](https://user-images.githubusercontent.com/50142231/227521125-bbdceb83-c152-45c9-9ad8-ae0bfd537570.png)
![Screen_230324_134513](https://user-images.githubusercontent.com/50142231/227521176-7da42b03-4299-4a4b-9f05-fe7f30a73aa4.png)

**Comment by WarLord211** [comment]
confirmed.
gear and flaps also not work
but its a tricky one, would need sometime.

**Comment by WarLord211** [comment]
So finaly i found a fix.
These Switches were affected: _Bomb Doors Lever; Chassis Lever; Flaps Lever; Rudder Trim; Aileron Trim; Elevator Trim; Aerial Winch Rotary Handle; R.1155 Aural Sense Switch_

(The trim switches are little tricky. if you send 0 or 2 the move full in the direction. if you just want a sep something you must send x and immediately 1)

Pls test them and report back

**Comment by Saylors** [comment]
Checked with Flight Radio Panel PZ69 (as far as possible) - it works. Thank you!
