### ISSUE TITLE
A-10C ii ARC-210 Channel knob only moves one direction

### ISSUE THREAD

**Issue by ColdFrontWI** [DCSFlightpanels/dcs-bios#159]
I've got my ARC-210 working except for the Channel knob (rotary encoder).  I can interact with it in DCS, but I can only **_increase_** the channel.  Not sure if this is a DCS-BIOS issue or something with the core game.  I've tried a few things, but the behavior remains the same.

By default, the control is implemented as an axis in clickabledata.lua, so I've tried a few modifications.  The original line is:
```
elements["VHFUHF2P"] = default_axis(_("ARC-210, channel select knob") , devices.VHF_AM_RADIO, device_commands.Button_27, 552, 1.0, 0.1, false, true)
```

I've tested three different alternatives:
```
elements["VHFUHF2P"] 	= multiposition_switch_tumb(_("ARC-210, channel select knob") , devices.VHF_AM_RADIO, device_commands.Button_27, 552, 40, 0.1)
elements["VHFUHF2P"] 	= multiposition_switch_tumb(_("ARC-210, channel select knob"), devices.VHF_AM_RADIO, device_commands.Button_1, 552, 40, 0.05, 0, false, 1)
elements["VHFUHF2P"] 	= multiposition_switch_tumb(_("ARC-210, channel select knob"), devices.VHF_AM_RADIO, device_commands.Button_1, 552, 40, 0.025, 0, false, 1)
```

In combination, I tried modifying the line in the DCS-BIOS A-10C.lua file from:
```
definePotentiometer("ARC210_CHN_KNB", 55, 3027, 552, {0, 1}, "ARC-210", "ARC-210 Channel Selector Knob")
```

To:
```
defineTumb("ARC210_CHN_KNB", 55, 3027, 552, 0.1, {0, 3.9}, nil, false, "ARC-210", "ARC-210 Channel Selector Knob")
```

I've used a couple of different versions of Arduino code with this:
```
DcsBios::RotaryEncoderT<POLL_EVERY_TIME, DcsBios::FOUR_STEPS_PER_DETENT> arc210ChnKnb("ARC210_CHN_KNB", "+3200", "-3200", A4, A5);
DcsBios::RotaryEncoderT<POLL_EVERY_TIME, DcsBios::FOUR_STEPS_PER_DETENT> arc210ChnKnb("ARC210_CHN_KNB", "INC", "DEC", A4, A5);
```

Since it is coded as an axis in clickabledata.lua by default, I also tried using a potentiometer.  The Arduino code I used for this was:
```
DcsBios::Potentiometer arc210ChnKnb("ARC210_CHN_KNB", A7);
```

No matter which of these approaches I take, the result is the same.  I can control the knob in DCS, but I can only ever **_increase_** the channel...never decrease.

Any other ideas to try?

Thanks,
Eric

**Comment by WarLord211** [comment]
Then it should be a rotary. Maybe.
Im on Travel. When im back I take a look

**Comment by ColdFrontWI** [comment]
FYI I was able to get this working.

I left the line in clickabledata.lua as it was:
```
elements["VHFUHF2P"] = default_axis(_("ARC-210, channel select knob") , devices.VHF_AM_RADIO, device_commands.Button_27, 552, 1.0, 0.1, false, true)
```

In the DCS-BIOS A-10C.lua file I replaced the line
```
definePotentiometer("ARC210_CHN_KNB", 55, 3027, 552, {0, 1}, "ARC-210", "ARC-210 Channel Selector Knob")
```

with
```
defineRotary("ARC210_CHN_KNB", 55, 3027, 552, "ARC-210 Radio", "ARC-210 Channel Selector Knob")
```

and paired that with DCS-BIOS Arduino code
```
DcsBios::RotaryEncoderT<POLL_EVERY_TIME, DcsBios::FOUR_STEPS_PER_DETENT> arc210ChnKnb("ARC210_CHN_KNB", "+1600", "-1600", PIN_A, PIN_B);
```

Seems to be working fine now!

Thanks,
Eric

**Comment by WarLord211** [comment]
i made the change too
