### ISSUE TITLE
Please add F-16 Mods support.

### ISSUE THREAD

**Issue by karpiyon** [DCSFlightpanels/dcs-bios#162]
Hi,
Can you please add, for next release support for the F-16 Mods.

I added locally:
in **F-16C_50.lua**:
`BIOS.protocol.setExportModuleAircrafts({"F-16C_50", "F-16D_50_NS", "F-16D_50",  "F-16D_52_NS", "F-16D_52", "F-16D_Barak_30", "F-16D_Barak_40", "F-16I"})`
in **AircraftAliases.json**:
```
              "F-16D_50": [ "CommonData", "F-16C_50" ],
           "F-16D_50_NS": [ "CommonData", "F-16C_50" ],
              "F-16D_52": [ "CommonData", "F-16C_50" ],
           "F-16D_52_NS": [ "CommonData", "F-16C_50" ],
        "F-16D_Barak_30": [ "CommonData", "F-16C_50" ],
        "F-16D_Barak_40": [ "CommonData", "F-16C_50" ],
                 "F-16I": [ "CommonData", "F-16C_50" ],
```
in **AircraftList.lua**:
```
a("F-16D_50_NS", true)
a("F-16D_50", true)
a("F-16D_52_NS", true)
a("F-16D_52", true)
a("F-16D_Barak_30", true)
a("F-16D_Barak_40", true)
a("F-16I", true)
```

**Comment by WarLord211** [comment]
are these mod all clickable? were did i get these?

(side note: AircraftAliases.json is auto generated [like all json] by BIOS no need to manual edit it)

**Comment by karpiyon** [comment]
Yes, all clickable
Got them from here:
https://discord.com/channels/853709103728820295/853713421937147915

**Comment by WarLord211** [comment]
done

**Comment by karpiyon** [comment]
thank you
