### ISSUE TITLE
Adding "Paddle Switch - Depress" tp F-16 code

### ISSUE THREAD

**Issue by karpiyon** [DCSFlightpanels/dcs-bios#164]
Hi,
Is it possible to add the "**_Paddle Switch - Depress_**" key to the F-16 code?
The key is: 
`{combos = {{key = '1', reformers = {'LCtrl','LWin'}}}, down = hotas_commands.STICK_PADDLE, up = hotas_commands.STICK_PADDLE, cockpit_device_id = devices.HOTAS, value_down = 1.0, value_up = 0.0, name = _('Paddle Switch - Depress'), category = {_('Stick'), _('HOTAS')}},`

**Comment by karpiyon** [comment]
> 

I know but this key IS clickable. I mapped it to keyboard keys and I can click it.

**Comment by WarLord211** [comment]
with mouse.
