### ISSUE TITLE
Update of User Guide needed

### ISSUE THREAD

**Issue by marsip** [DCSFlightpanels/dcs-bios#165]
I'm a totaly new user of DCS-bios and even DCS. I'm reading the User Guide tryint to follow the steps. But some is confusing.

**Step 4, So lets begin** 
- The text says "Click File->Examples->DcsBios->TemplateSketch", but my Arduino IDE (ver 2.1.0) has no "TemplateSketch" entry. Instead I choosed "IRQSerial"
-  "Go to your saved Games folder/DCS-BIOS/doc and double-click on the file control-reference.html". It should read: Games folder/**Scripts/**DCS-BIOS/doc
- The text should read in beginning: Select the desired aircraft module in the "Module" list.
- I assume the Category Filter entries are depended on what aircraft module you have selected. The AJS37 aircraft, which I use, has no "Up Front Controller" entry, but managed to find the Master Caution lamps and reset in other place in the list.
- In the code example, before saving the sketch, has an entry: "#include <Servo.h>". My sketch file has no such entry. Maybe because I didn't find and used the TemplateSketch file.

**Step 6**
- "Open the connect-serial-port.cmd file which is in the DCS-BIOS folder you previously downloaded. " Confusing. What map is referenced? I found it in the unpacked zip folder "dcs-bios-master/Programs"

**Comment by WarLord211** [comment]
Hi

Step 4

* I cant find TemplateSketch in the user guide?! I found in every document IRQSerial. which guide have you read?
* Corrected
* added
* In the example is the A-10 other airplane other names. Should be clear as it is
* never heart of TemplateSketch (see point 1)

Step 6
*i rewrite this
