### ISSUE TITLE
json file name for F-15ESE

### ISSUE THREAD

**Issue by emcek** [DCSFlightpanels/dcs-bios#166]
Hello,
Can you follow convention of naming JSON files, which aircraft name reports BIOS and JSON spec fail, i.e.:
* `FA-18C_hornet` -> `FA-18C_hornet.json`
* `F-16C_50` -> `F-16C_50.json`

but:
* `F-15ESE` -> `F-15E.json`

It will make my live easier (less `if`s in code)

**Comment by WarLord211** [comment]
F-15ESE is not a good name in my opinion. so i use F-15E.
whats the problem with that?

**Comment by emcek** [comment]
Generally is not big deal, I use DCS-BIOS name:
```json
{"address": 0,
"description": "Aircraft Name (or NONE), null-terminated",
"max_length": 24}
```
To download/load and parse JSON. And in all cases (F-14, F-16, F-18, A=10, Ka-50 etc.) they match but not for F-15. Anyway I will hardcode it or parse `AircraftAliases.json`.

Feel free to close this issue.
