### ISSUE TITLE
AJS37 missing values

### ISSUE THREAD

**Issue by marsip** [DCSFlightpanels/dcs-bios#170]
I was trying to access values from the Angle of Attack instrument (upper left, jgp incluced), but didn't find this value in the control-reference document. Instead I tried to use the "ADI AoA Indicator" from the Raw Gauge Values. But this value is mostly zero, and don't indicate AoA. By change I found the value (ADI AoA Indicator) was following the Engine nozzle indicator (right side, jpg included)! But the nozzle indicator is not in the control-reference document!?

I'm using dcs-beta updated to latest version, and have installed the latest dcs-bios version.

![Alfainstrument](https://github.com/DCSFlightpanels/dcs-bios/assets/34987099/60141297-6192-4196-bce3-3b960d969772)
![MunstyckeEBK](https://github.com/DCSFlightpanels/dcs-bios/assets/34987099/9306ee85-d509-4595-a6a9-f9bf0914e850)

**Comment by WarLord211** [comment]
Booth fixed. The address of the "ADI AoA Indicator" has changed.
I found some others too. i assume there are more problems/falsea arguments/ missing items.

if you find more feel free to open issues. 
The BIOS file of this plane needs an overhaul

**Comment by marsip** [comment]
If have downloaded the latest version and tested. Both Angle of Attack and Engine nozzle indicators are ok now.
