### ISSUE TITLE
F-15E Line 5 and 6 and Line 5 and 6 (special characters) not following other line patterns

### ISSUE THREAD

**Issue by RafaPolit** [DCSFlightpanels/dcs-bios#171]
Good evening,

Thanks so much for the quick addition of the F-15E.

The solution for having Line N present the main characters and Line N (special characters) present the dot, apostrophe, or colon is very clever and works perfectly.

On Line 5 and 6 though, this is not really working as expected.

For a Line 5 display of ` U262.000   U133.000*`, you get:
Line 5 data reads, for example: ` U262000     U133000*`
Line 5 (special characters) does not include any of the  dots you can see between the 262.000 and 133.000 on the UFC display on the plane.

Line 6 is even more "wrong" as the data in Line 6 (special characters) is actually rendering the NORMAL characters input on the keyboard, and not respecting the special characters AT ALL.

For example, for an UFC Line 6 input of a coordinate which would read like `*G      N34'25.345    GV*` on the plane display, we get:
Line 6 data: `*G                     GV*`
Line 6 (special characters): `         N3425345       `

As you can see, the apostrophe and dot that SHOULD be on the special characters line don't show, and we actually get the values input on the keyboard, which should belong to the normal Line 6 data.

Thanks for looking into this, much appreciated, best regards,
Rafa.
edit: my spaces are just "for demonstration purposes", some lines could have more or less than 20 characters, it's just to understand the concept.

**Comment by WarLord211** [comment]
noted! we look into it.

**Comment by RafaPolit** [comment]
Thanks!

May I also ask what is the reason to have the Line 2A Left, Line 2B Left, etc. output instead of including the `'`, `.` and ':` on the special characters spaces for each line?  I not only fail to see the reason for the separation, I also have no idea what criteria to use on which characters to put them on: is it always the 3rd on line 2 and the fourth on line 3?  It's a bit confusing, so I'd appreciate the reasoning behind it if you can. Thanks!

**Comment by Maverick87Shaka** [comment]
Hi @RafaPolit ,
Basically it's a problem of how it's implemented on DCS, and how far we can go trying with "workaround" to make it simpler to use with DCS-Bios. 

Line 6 doesn't include the UFC user input in the variable, and try to combine radio and user input from DCS-BIOS it's almost impossible due to variable string length and a BUG that currently allow player to input more characters that one should be in real I guess.  (you can replicate start typing on UFC, you see you can overlap other display info)

I'm sorry for the lack of documentation, it's a pending task on my end, I'll try to make it available later. 2AL 2B etc should be the variable that you have to grab and place for line 5 and 6 dots, but from a quick test with bort they looks empty at the moment

I'll take a closer look in the next days.

Here below an example of current variable layout

![F-15E_UFC](https://github.com/DCSFlightpanels/dcs-bios/assets/51521/1e790660-13a4-4b80-91d4-787dd493c63a)


![F-15E_UFC_Layout](https://github.com/DCSFlightpanels/dcs-bios/assets/51521/d64d7aed-af3e-49fc-b832-e6caf1d18e34)

**Comment by RafaPolit** [comment]
I believe I can help.  If you could jump-start me on one thing: what are you using to output those values on the right?  So, bottom line, what flow do you use to print that output on a file / console?  In the past I have created buttons and triggers to dump that on a file, but it’s pretty time consuming.  If there is a way to check those values quickly, I can look into the logic of combining them, if it helps.Thanks again,Rafa PólitOn 29 Jun 2023, at 02:57, Padovani Andrea ***@***.***> wrote:﻿
Hi @RafaPolit ,
Basically it's a problem of how it's implemented on DCS, and how far we can go trying with "workaround" to make it simpler to use with DCS-Bios.
Line 6 doesn't include the UFC user input in the variable, and try to combine radio and user input from DCS-BIOS it's almost impossible due to variable string length and a BUG that currently allow player to input more characters that one should be in real I guess.  (you can replicate start typing on UFC, you see you can overlap other display info)
I'm sorry for the lack of documentation, it's a pending task on my end, I'll try to make it available later. 2AL 2B etc should be the variable that you have to grab and place for line 5 and 6 dots, but from a quick test with bort they looks empty at the moment
I'll take a closer look in the next days.
Here below an example of current variable layout

**Comment by RafaPolit** [comment]
I see what you mean about the bottom line being able to overlap:
![image](https://github.com/DCSFlightpanels/dcs-bios/assets/4309019/0074ae69-2e9e-4289-b9fb-da2262e2b231)

But I think this is a "placement" error, as the chars don't even coincide, and that is THE LAST character you can type, so I believe can safely start "one character early" with the central input at the bottom?

**Comment by RafaPolit** [comment]
I can also see the problem with parsing the values.  In the above example the parsed string in the first line the string is `061'/3.0`, and both the apostrophe (°) and the dot need to be "separated" to the special characters, but the `7'` on the second line should use the "in line" apostrophe.  I believe that is a problem of using the apostrophe as  the escape character for the degrees.  Perhaps that is easier to just use another character?

I am now exporting the RAW values, so I have quick access to debugging, so no need to help with my request on the flow.  I have it covered. Thanks.

**Comment by RafaPolit** [comment]
I believe that most of the values are always the same location on the same line, except for `UFC_LL_INPUT_MIN` and `UFC_LL_INPUT_DEG` which vary depending on the length of UFC_CC_04 (7 or 8 chars) when it begins with `N` or `E` or `S` or `W` (or maybe they are right-position fixed)

I am starting to believe that a Line by Line approach could be more elegant.  I'll keep on documenting my findings here if it is of any use.

**Comment by RafaPolit** [comment]
Another issue is that the special character replacing algorithm is wrong.  If you have `1:23:45`, the special characters should be `: :`, that is the first colon and the second one should only have one space in between: the one corresponding to the 2 (as the 1 and 3 are the actual colon characters).  By simply removing the characters with `[^.:°]` you assign two characters in between, which is not correct.

**Comment by RafaPolit** [comment]
I honestly don't know how I got the D2A and D2B keys to show, if someone has the info how to make them "hold data" it would be highly appreciated.
