### ISSUE TITLE
P-47-D-40, Detrola LF Radio

### ISSUE THREAD

**Issue by jdahlblom** [DCSFlightpanels/dcs-bios#174]
I implemented this radio in DCSFP and noticed that there is something wrong.
DETROLA_FREQU_SEL which should change the frequency seems to change the volume dial for the Detrola. But it seems random. Sets a fixed value.
DETROLA_VOL, regardless if I put 5000 or -5000 in ctrlref the dial's value increases. And it doesn't change with the value given.

**Comment by jdahlblom** [comment]
I noticed problems with P-51D too.
BUT :
Although variable_step is broken then set_state works. So I will use that instead. That is enough for me.

**Comment by WarLord211** [comment]
wich control for the P-51?

fix for P-47 is inbound

**Comment by jdahlblom** [comment]
`definePotentiometer("DETROLA_FREQU_SEL", 24, 3001, 137, {0, 1}, "Detrola Receiver", "Detrola Frequency Selector")
definePotentiometer("DETROLA_VOL", 24, 3002, 138, {0, 1}, "Detrola Receiver", "Detrola Volume")`

**Comment by WarLord211** [comment]
thats for P-47 its fixed.
i mean the P-51 bug.

**Comment by jdahlblom** [comment]
OK so I closed the issue too early. And I was mixed the airplanes up, I was testing the Detrola on the P-51 and the set_state worked there but set_state does not work on P-47D.

**Comment by jdahlblom** [comment]
OK will test the fix! Thanks!!

**Comment by WarLord211** [comment]
-> discord

**Comment by WarLord211** [comment]
P-51 works as it should? can find a bug

**Comment by jdahlblom** [comment]
set_state for P-47D works now.
