### ISSUE TITLE
a problem with the VHF of the M2000C

### ISSUE THREAD

**Issue by yakisyst3m** [DCSFlightpanels/dcs-bios#176]
hello, there is a bug with the VHF M2000C. When I change radio channel, there is a shift of 1 on the VHF: "channel selector VHF_CH_SEL". In DCS-BIOS it goes from 0 to 19 while in the mirage 2000C it goes from 1 to 20.

**Comment by WarLord211** [comment]
I think its BIOS more BIOS related than Flightpanels.

which BIOS version do you use?

**Comment by yakisyst3m** [comment]
Hello. I use DCS-BIOS 0.7.48.

**Comment by yakisyst3m** [comment]
I noticed that I manage to correct the problem with XFR. When I change the radio to XFR mode, the preset is frozen. I will install the latest DCS-BIOS
