### ISSUE TITLE
Attempt to concatenate local 'identifier' (a nil value)

### ISSUE THREAD

**Issue by emcek** [DCSFlightpanels/dcs-bios#179]
Running master branch (d8459215d2ad51bbac4c578faefd9261050bb448) for all planes I got:
```
2023-08-16 09:51:06.768 ALERT   EDCORE (Main): Can't execute Lua file D:\Users\xxxxx\Saved Games\DCS.openbeta\Scripts\Export.lua - [string "D:\Users\xxxxx\Saved Games\DCS.openbeta\Scripts\DCS-BIOS\lib\Util.lua"]:39: attempt to concatenate local 'identifier' (a nil value)
```
And no data to export....
0.7.49 is of course fine.

**Comment by WarLord211** [comment]
confirmed! WIP

**Comment by maciekish** [comment]
This is probably my bad, i'll have a look at it in a few hours.

**Comment by maciekish** [comment]
At a glance this looks like a missing module name or control identifier. 

1) Did you make any changes to any files?
2) Which module did you attempt to load? I don't think it matters but good to know anyway.

**Comment by WarLord211** [comment]
1. no changes (except in the luas: Version Numbers and Change dates; all outcommanded)
2. all modules looks like bios crashes before it gets module data

**Comment by emcek** [comment]
> At a glance this looks like a missing control identifier.
> 
> 1. Did you make any changes to any files?
> 2. Which module did you attempt to load? I don't think it matters but good to know anyway.

1. no
2. try A-10C, A-10C2 and F-16 but looks like it do not matter

**Comment by maciekish** [comment]
Thanks. I'll have a look soon.

**Comment by maciekish** [comment]
I have fixed this and submitted a new PR https://github.com/DCSFlightpanels/dcs-bios/pull/180

**Comment by emcek** [comment]
Yes it is working.
