### ISSUE TITLE
F/A-18C Hornet / Uncorrect action on SNSR Panel

### ISSUE THREAD

**Issue by Winters91** [DCSFlightpanels/dcs-bios#182]
Hi all,

Since yesterday I'm trying to code an Arduino MEGA2560 for the SNSR Panel and some codes of the BIOS doesn't seems to work properly on the game.

1st example:

**DcsBios::Switch2Pos lstNflrSw("LST_NFLR_SW", 10);** Does not operate the LST/NFLR switch in the game but the FLIR one... first try FLIR OFF to STBY and second try STBY to ON. No return possible.

2st example:

**DcsBios::Switch2Pos ltdRArm("LTD_R_ARM", 10);** Does not operate the LTD/R switch in the game but the LST/NFLR one.

The FLIR code line seems to works fine, INS too. I didn't check the RDR one.

What could be the issue ? Could it be a DCS update that cause this problem ? Or a malfunction in the BIOS ? 

Thanks !

Winters91

**Comment by WarLord211** [comment]
Bios Version?

**Comment by Winters91** [comment]
V0.10.0 (+64) according to my BIOS Web Interface. The latest one normally ?

**Comment by WarLord211** [comment]
This Version of bios has no maintainer and is ATM unsupported. F18 is waaay outdated.
Use Our fort instead

**Comment by Winters91** [comment]
All right then, thanks for the advice !
