### ISSUE TITLE
Cant get the Console lights potentiometer to work in my f22 home cockpit

### ISSUE THREAD

**Issue by Lkirchner1234** [DCSFlightpanels/dcs-bios#185]
I have tried a bunch of other variables in f22 with the same potentiometer and they work. For some reason however the console lights doesnt work. This is my code: DcsBios::Potentiometer consoleLightsSw("CONSOLE_LIGHTS_SW", 2); . I put it in the IRQserial example and it doesnt work. Any help would be great.

**Comment by WarLord211** [comment]
Is fixed in Master.

**Comment by Lkirchner1234** [comment]
What does that mean?

**Comment by WarLord211** [comment]
I found the error and in the master branch (green button on the main side) its uploaded. With the next stable patch of dsc it is in the next release. 
How to download and use the master branch there is an instruction in the doc folder

**Comment by Lkirchner1234** [comment]
Thank you!
