### ISSUE TITLE
When I use the code from the control reference for the panel LEDs for the f22 they turn on and off but brightness doesn’t work.

### ISSUE THREAD

**Issue by Lkirchner1234** [DCSFlightpanels/dcs-bios#186]
I have been trying to backlight my panels using dcs bios for the f22 but the code that I found for it won’t let me control the brightness it only turns it on and off. Any help?

**Comment by WarLord211** [comment]
The LED must be rewrite for this.
I do it later when im home

**Comment by Lkirchner1234** [comment]
Ok, thank you. Tell me when it’s done.

**Comment by WarLord211** [comment]
there new LEDs as float. it generates an % valve were you can convert in brightness

**Comment by Lkirchner1234** [comment]
How do I do that?

**Comment by Lkirchner1234** [comment]
Also, I tried putting the variables that are in that code into the arduino code and it doesn't work.

**Comment by Lkirchner1234** [comment]
It is still only turning it on and off.

**Comment by Lkirchner1234** [comment]
Help?

**Comment by WarLord211** [comment]
Use the Leds with (as float) in decription.
you get now a valve with that you can generate a dim function in arduino. For this pls concider the forum or our Discord

**Comment by Lkirchner1234** [comment]
I have joined the discord but no one really responded

**Comment by Lkirchner1234** [comment]
And the forum has nothing on using floats or like a gauge on percent of a led. Could you please tell me a little more?

**Comment by Lkirchner1234** [comment]
Help?
