### ISSUE TITLE
Duplicate keys

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#187]
#### `CC_FRONT_WP_NORM`
https://github.com/DCSFlightpanels/dcs-bios/blob/3e40d24f17901c5c0f69afa735c0f2fe5dfa3717/Scripts/DCS-BIOS/lib/C-101.lua#L610
https://github.com/DCSFlightpanels/dcs-bios/blob/3e40d24f17901c5c0f69afa735c0f2fe5dfa3717/Scripts/DCS-BIOS/lib/C-101.lua#L825

### MB-339
- `AFT_CONTROL_ADF`
- `AFT_CONTROL_ILS`
- `AFT_CONTROL_NAV`
- `AFT_CONTROL_TCN`
- `FW_CONTROL_ADF`
- `FW_CONTROL_ILS`
- `FW_CONTROL_NAV`
- `FW_CONTROL_TCN`
https://github.com/DCSFlightpanels/dcs-bios/blob/3e40d24f17901c5c0f69afa735c0f2fe5dfa3717/Scripts/DCS-BIOS/lib/MB-339.lua#L447-L472

- `WP_STAT1_G`
- `WP_STAT2_G`
- `WP_STAT3_G`
- `WP_STAT4_G`
- `WP_STAT5_G`
- `WP_STAT6_G`
https://github.com/DCSFlightpanels/dcs-bios/blob/3e40d24f17901c5c0f69afa735c0f2fe5dfa3717/Scripts/DCS-BIOS/lib/MB-339.lua#L545-L560

**Comment by WarLord211** [comment]
Thanks!
 internal fixed upload with next beta patch od DCS

**Comment by charliefoxtwo** [comment]
Looks good, thanks!
