### ISSUE TITLE
Code to export screens from the dcs bios forum doesn't completely work for the f22

### ISSUE THREAD

**Issue by Lkirchner1234** [DCSFlightpanels/dcs-bios#193]
I used the export script from the dcs bios forum and it worked for the f22 but if I go to the radar page on the pmfd it does not appear and if I go to the sms page on the left mfd it doesn't appear and if I go to the rwr page on the right mfd it also doesn't appear. Is this fixable or is it just the case because it relies on the f15 for these screens?

**Comment by WarLord211** [comment]
These exports are not bios relaxed. Bios handle only the Switches

**Comment by Lkirchner1234** [comment]
Ok.
