### ISSUE TITLE
Can't figure out how to use float commands to control brightness of led

### ISSUE THREAD

**Issue by Lkirchner1234** [DCSFlightpanels/dcs-bios#194]
A dcs bios noob here.

I found this comment on the dcs forum for an a10 user who is trying to backlight his panels and he kind of explains what I am trying to do. 
https://forum.dcs.world/topic/233647-dcs-bios-a-10-panel-backlighting-enable/?do=findComment&comment=4274157
The only thing is that he said remap to pwn and I have no idea what it is and can't figure it out.

Any help would be great.

**Comment by Lkirchner1234** [comment]
Also this is for the f22 by grinnelli.

**Comment by WarLord211** [comment]
For questions about bios programming, I recommend to join our discord. Link at the main page of github

**Comment by Lkirchner1234** [comment]
Ok

**Comment by Lkirchner1234** [comment]
I sent a chat waiting for someone to respond...
