### ISSUE TITLE
Yak-52 duplicate keys

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#21]
Currently the Yak-52 has the key `FRONT_RADIO_VOL` used for two separate controls. Is this intentional? I have no experience in it, but my understanding was that all keys should be unique (per aircraft). If I sent a command to DCS-BIOS to update `FRONT_RADIO_VOL`, which control would be updated?

Changing this could also potentially be a breaking change for somebody.

```
----- SPU-9
definePotentiometer("FRONT_ICOM_VOL", 28, 3001, 80, {0, 1}, "SPU9", "Fore Intercom Volume Knob")
definePotentiometer("FRONT_RADIO_VOL", 28, 3004, 81, {0, 1}, "SPU9", "Fore Radio Volume Knob") -- here
defineToggleSwitch("FRONT_ICOM_STBY_DISTR_SW", 28, 3007, 82,"SPU9" , "Fore Intercom STBY Distributive Switch")
defineToggleSwitch("FRONT_ICOM_RDF_SW", 28, 3009, 83,"SPU9" , "Fore Intercom RDF Switch")
----- BAKLAN-5
definePotentiometer("FRONT_RADIO_VOL", 27, 3002,  90, {0, 1}, "BAKLAN-5", "Fore Radio Volume Knob") -- and also here
defineRotary("FRONT_RADIO_MHZ", 27, 3011, 88, "BAKLAN-5", "Fore Radio Tune mhz")
defineRotary("FRONT_RADIO_KHZ", 27, 3008, 89, "BAKLAN-5", "Fore Radio Tune khz")
defineToggleSwitch("FRONT_RADIO_SQ", 27, 3020, 91,"BAKLAN-5" , "Fore Radio Squelch")
```

**Comment by WarLord211** [comment]
thats a copy past error. thanks for that

**Comment by WarLord211** [comment]
Fixed.
i changed the whole BAKLAN-5 radio entrys.
Fix uploaded to the master branch, will be in next Release

**Comment by charliefoxtwo** [comment]
I don't have the Yak-52 so I can't test per se.

I came across this when parsing the json with a tool I'm writing, and that was the one duplicate key I came across in all of the json files. The commit you pushed seems to address the issue, so I'll go ahead and close this. Thanks for the fix!
