### ISSUE TITLE
UH-1H VHF Nav control interference

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#23]
I haven't looked too closely into what's going on here, but incrementing/decrementing `VHFNAV_KHZ` seems to also affect the state of  `VHFNAV_VOL` in BIOS (though, not visually in game). While these controls are situated on top of each other in the module, modifying one should *not* modify the other.

Edit: It appears there is also a similar problem with `VHFNAV_MHZ` and `VHFNAV_PWR`

Repro steps:
 1. load into Huey
 2. open UH-1H > VHF NAV Radio in BIOS
 3. press INC/DEC for `VHFNAV_KHZ`
 4. observe state of `VHFNAV_VOL` changes by variable step suggested step amount

![hueybiosinterference](https://user-images.githubusercontent.com/30303272/102729351-4b1bf700-42e5-11eb-9c0a-c93112c94c4b.gif)

**Comment by charliefoxtwo** [comment]
Noticing a few other issues with the Huey as well:
 - `ROCKET_SEL` seems to have 3 positions, but in the module it only has 2. I can't really tell whether or not it's _supposed_ to have 3, but what I can say is if there is a 3rd position I can't find any way to select it.
 - `JTSN_COVER` seems to have 3 positions, when again it only has 2 in the module. I tried changing the lua to fix this, but bios then showed the open state as "50%" so I'm not really sure what's going on here.
 - `ADF_MODE` has 3 positions in BIOS, but the module has 4 positions. The multiposition switch state count can simply be updated to 4 on this one, and it will work as expected.

**Comment by WarLord211** [comment]
thx for the perfekt report. i check this

**Comment by WarLord211** [comment]
JTSN_COVER and ADF_MODE is fixed

**Comment by WarLord211** [comment]
pls test it

**Comment by charliefoxtwo** [comment]
Both seem correct to me, thanks for the quick fix!

Regarding `ROCKET_SEL`: understood, makes sense to me.
