### ISSUE TITLE
VNAO_Room Duplicate key

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#24]
I have a program that loads in DCS BIOS's configuration data for its own use, and I noticed when running it on the latest version of DCS BIOS that the key `LIGHTS` appears twice in VNAO_Room. I don't know anything about VNAO_Room so feel free to close if this is intended, but this is the only duplicate key issue in all of the modules so I'm assuming it's not intended.

Offending lines in VNAO_Room.lua:
18: `defineToggleSwitch("LIGHTS", 6, 10003, 387, "Systems", "Light Switch")`
29: `defineFloat("LIGHTS", 387, {0, 1}, "Gauges", "Lights")`

**Comment by WarLord211** [comment]
Thx is fixed
