### ISSUE TITLE
C-101CC Radio Knobs Do Not Work As Expected

### ISSUE THREAD

**Issue by asherao** [DCSFlightpanels/dcs-bios#25]
The V/UHF, VHF, VOR, NAV, and ADF knobs do not work as expected via DCS-BIOS Control Reference Live Preview with the C101CC. 

V/UHF - Cannot set a new set_state and have it be properly represented in DCS set_states higher than 2 only INC. 
VOR/NAV - INC, DEC, and set_state only INC. Cannot set a set_state.
ADF - Most changed values in the Live Preview are either not reflected ingame, not reflected in the Live Preview, or both. In at least two cases, changing a Live Preview value will result in a different Live Preview being changed.

An unknown number of C101EB UHF commands change C101CC UHF rotary positions.

**Comment by WarLord211** [comment]
> An unknown number of C101EB UHF commands change C101CC UHF rotary positions.

thats not changeable since the share the same arguments. >Thats the reason why the named CC and EB in front

rest i will look

**Comment by asherao** [comment]
- **C-101CC FRONT ADF Left Frequency Selector 0.5 kHz** C-101CC/CC_FRONT_ADF_FREQ_L_05
- **C-101CC FRONT ADF Left Frequency Selector 10 kHz** C-101CC/CC_FRONT_ADF_FREQ_L_10
- **C-101CC FRONT ADF Left Frequency Selector 100 kHz** C-101CC/CC_FRONT_ADF_FREQ_L_100
- **C-101CC FRONT ADF Right Frequency Selector 0.5 kHz** C-101CC/CC_FRONT_ADF_FREQ_R_05
- **C-101CC FRONT ADF Right Frequency Selector 10 kHz** C-101CC/CC_FRONT_ADF_FREQ_R_10
- **C-101CC FRONT ADF Right Frequency Selector 100 kHz** C-101CC/CC_FRONT_ADF_FREQ_R_100

- **C-101CC FRONT UHF Radio 0.025 MHz Selector** C-101CC/CC_FRONT_UHF_SEL0025
- **C-101CC FRONT UHF Radio 0.1 MHz Selector** C-101CC/CC_FRONT_UHF_SEL01
- **C-101CC FRONT UHF Radio 1 MHz Selector** C-101CC/CC_FRONT_UHF_SEL1
- **C-101CC FRONT UHF Radio 10 MHz Selector** C-101CC/CC_FRONT_UHF_SEL10
- **C-101CC FRONT UHF Radio 100 MHz Selector** C-101CC/CC_FRONT_UHF_SEL100

- **C-101CC FRONT VHF COMM Frequency Control 10 kHz** C-101CC/CC_FRONT_VHF_COMM_FREQ_10
- **C-101CC FRONT VHF COMM Frequency Control 100 MHz** C-101CC/CC_FRONT_VHF_COMM_FREQ_100
- **C-101CC FRONT VHF NAV Frequency Control 1 MHz** C-101CC/CC_FRONT_VHF_NAV_FREQ_1
- **C-101CC FRONT VHF NAV Frequency Control 50 kHz** C-101CC/CC_FRONT_VHF_NAV_FREQ_50

**Comment by WarLord211** [comment]
UHF is fixed , Half of VHF. ADF is strange

**Comment by asherao** [comment]
I won't be able to confirm the fix myself. Thank you.

**Comment by WarLord211** [comment]
UHF, VHF fixed. ADF 2 of 6 fixed

**Comment by WarLord211** [comment]
Fixed
