### ISSUE TITLE
L-39ZA Pitot Tube Commands Are Mixed Up

### ISSUE THREAD

**Issue by asherao** [DCSFlightpanels/dcs-bios#26]
When trying to monitor the status of the pitot tube buttons, for example, I press Main Pitot Heating On, but Standby Heating Off is toggled in the DCS-BIOS Live Preview. I get different, but still odd and incorrect results when trying to modify the panel using Live Preview. I cannot determine the logic. It does not seem like a simple switch of two numbers.
Effected Controls: (L-39ZA/Electric System)
- **Standby (Left) Pitot Tube Heating OFF Button** L-39ZA/PITOT_HEAT_OFF_L
- **Main (Right) Pitot Tube Heating OFF Button** L-39ZA/PITOT_HEAT_OFF_R
- **Standby (Left) Pitot Tube Heating ON Button** L-39ZA/PITOT_HEAT_ON_L
- **Main (Right) Pitot Tube Heating ON Button** L-39ZA/PITOT_HEAT_ON_R
DCS-BIOS 0.7.38

**Comment by WarLord211** [comment]
fix uploaded to Master branch. 
Some Argument Numbers were switched

**Comment by asherao** [comment]
Tested. Working as expected. 👍
Thank you.
