### ISSUE TITLE
L-39ZA - FRONT_BOMB_REL_SEL 0 Puts Switch In Intermediate Position Instead of Down

### ISSUE THREAD

**Issue by asherao** [DCSFlightpanels/dcs-bios#27]
FRONT_BOMB_REL_SEL 0 puts the switch in the position shown in the picture instead of full down. FRONT_BOMB_REL_SEL 1 puts the switch up (which is correct). 

![image](https://user-images.githubusercontent.com/15984377/103437359-28d19400-4c6a-11eb-8f0c-19fe02928599.png)

It may be an animation argument error.

**Comment by asherao** [comment]
This can be observed in the Live Previewer.

**Comment by asherao** [comment]
The function of the switch seems to be correct. I can use starboard weapons even in the visually intermediate state.

**Comment by WarLord211** [comment]
fix uploaded to Master branch. 
Some Argument Numbers were switched

pls test it

**Comment by asherao** [comment]
Tested. Working as expected. 👍 
Thank you.
