### ISSUE TITLE
L-39ZA - FRONT_ROCKET_MODE 0 Puts Switch In Intermediate Position Instead Of A Position

### ISSUE THREAD

**Issue by asherao** [DCSFlightpanels/dcs-bios#28]
![image](https://user-images.githubusercontent.com/15984377/103438590-a354e080-4c77-11eb-8d2a-97e57eef5d14.png)

The picture above is when FRONT_ROCKET_MODE 0 is used from the Live Previewer. This switch should not have a center position like that. It is a three way switch, the directions indicated by the cutouts.

FRONT_ROCKET_MODE 1 goes to the "Train" position. 
FRONT_ROCKET_MODE 2 goes to the "2" position.

**Comment by asherao** [comment]
It seems that the weapon operation itself is correct. 
![image](https://user-images.githubusercontent.com/15984377/103438708-32162d00-4c79-11eb-9371-28dbcbab400f.png)

**Comment by WarLord211** [comment]
fix uploaded to Master branch. 
Some Argument Numbers were switched

pls test it

**Comment by asherao** [comment]
Tested. Working as expected. 👍 
Thank you.
