### ISSUE TITLE
C-101 HUD Depression Selector "set_state" Does Not Work As Intended 

### ISSUE THREAD

**Issue by asherao** [DCSFlightpanels/dcs-bios#30]
C-101CC/Colimador:
- **C-101CC FRONT HUD Depression 0XX** C-101CC/CC_FRONT_HUD_DEPRESS_0XX
- **C-101CC FRONT HUD Depression X0X** C-101CC/CC_FRONT_HUD_DEPRESS_X0X
- **C-101CC FRONT HUD Depression XX0** C-101CC/CC_FRONT_HUD_DEPRESS_XX0

The "set_state" for the above controls via the Live Previewer do not work as intended. When "set_state" is above zero, they increase by one. When "set_state" is zero, they decrease by one.

In addition, the "set_state" for C-101CC FRONT HUD Depression 0XX goes from "0" to "9", but there are only 3 positions that the dial can be in.

Image of the Depression Selector for reference: 
![image](https://user-images.githubusercontent.com/15984377/103455873-32bfc980-4d34-11eb-93e1-a75779cc0aff.png)

**Comment by WarLord211** [comment]
fix uploaded to Master branch.
changed switch type

pls test it

**Comment by asherao** [comment]
I won't be able to confirm the fix myself. Thank you.
