### ISSUE TITLE
STM32 support - can it be scooped up from original BIOS repo?

### ISSUE THREAD

**Issue by virtual812** [DCSFlightpanels/dcs-bios#34]
Hi there,

Asked about STM32 support in the original Arduino library repo a while back, seems no one is active there.
Was looking yesterday and just happened to see that there was a pull request there from someone who had added STM32 support.

Given the depth of my panels the Arduino mega 2560 has run out of space, is there any chance this repo could include the changes that allow STM32 support?

Are the devs here open to other suggestions / requests?

Thanks for your effort,
Virt.

**Comment by talbotmcinnis** [comment]
Hi Virtual82.  Yes, dcs-bios is actively developed under flight panels, here is a link to the repo. Sorry to be a pain, but if you wouldn't mind opening the issue on that repo, We can see what is required to support that!

https://github.com/talbotmcinnis/dcs-bios-arduino-library

**Comment by WarLord211** [comment]
like talbotmcinnis said. the arduino side is "moved" to him.
Here is more the plane side of it
