### ISSUE TITLE
UH-1H Pilot Sight Armed / Safe Seems To Work As Toggle With Any Control

### ISSUE THREAD

**Issue by asherao** [DCSFlightpanels/dcs-bios#35]
UN-1H
Flex Sight
Pilot Sight Armed / Safe (UH-1H/SIGHT_ARM_PLT)
When using the live previewer, every button seems to act as a toggle instead of fixed_step or set_state.

**Comment by WarLord211** [comment]
fix uploaded pls test it

**Comment by asherao** [comment]
I downloaded dcs-bios-master.zip, unzipped it, dragged the DCS-BIOS folder over the Saved Games location, overwrote the files, reinstalled the Live Previewer. There seems to be no change.

**Comment by WarLord211** [comment]
then i dont understand the problem

**Comment by WarLord211** [comment]
Ok got it what you mean.
Problem comes from the way how its done in the Module from DCS side.
Ist not a Switch, its programed like a part of an multi Pos switch.

i see no way to change that behavior

**Comment by asherao** [comment]
Ok.
