### ISSUE TITLE
UH-1H Door Left/Right Seems To Work As Toggle With Any Control

### ISSUE THREAD

**Issue by asherao** [DCSFlightpanels/dcs-bios#36]
Similar issue as https://github.com/DCSFlightpanels/dcs-bios/issues/35.
UH-1H
Doors
Door Left (UH-1H/DOOR_L-PTR)
Door Right (UH-1H/DOOR_R-PTR)
When using the live previewer, INC, set_state 1, and TOGGLE work as toggles.
DEC and set_state 0 do not work.

**Comment by WarLord211** [comment]
1 is for Handel down; 0 for handle up.

Handel is "spring loaded" so open a door is alwas 1 and 0

open Live preview and click the door than you will see it.
Hardware side it will be a push button

**Comment by asherao** [comment]
Makes sense. Thank you.
