### ISSUE TITLE
UH-1H Radar Altimeter High Setting does not show current value

### ISSUE THREAD

**Issue by asherao** [DCSFlightpanels/dcs-bios#37]
When using the Live Previewer, the "Current Value" is not shown for the Radar Altimeter High Setting. There may be an issue with the DCS model because the knob does not stop turning if you manually turn it past the bottom (zero feet).
UN-1H
Front Dash
Radar Altimeter High Setting (UH-1H/RADAR_ALT_HI)

**Comment by WarLord211** [comment]
False Argument - Fixed
