### ISSUE TITLE
AV8B - Channel Knobs, PZ069

### ISSUE THREAD

**Issue by Frozeph** [DCSFlightpanels/dcs-bios#38]
The channel knobs for the AV8B don't work with the PZ069. 

Current version of DCS-Bios and Flightpanels. 

How can I see if DCS-Bios picks up the changes made in game?

**Comment by WarLord211** [comment]
via the Live Preview / Ref Page (a chrome browser app)

i tested and the dont work correct

will fix this

**Comment by WarLord211** [comment]
fix uploaded

**Comment by Frozeph** [comment]
Thank you so much for the quick turnaround, I will test this evening after work.

**Comment by Frozeph** [comment]
I have tested and confirmed that is working now. Thank you so much for the super quick turn around.

**Comment by Frozeph** [comment]
I have tested and confirmed that is working now. Thank you so much for the super quick turn around.
