### ISSUE TITLE
F-16C AN/ARC-164 Radio Channel/Frequency Data not exporting

### ISSUE THREAD

**Issue by wiggles5289** [DCSFlightpanels/dcs-bios#42]
F-16C Radio Channel Frequency is not exporting any data, just shows nothing. Data exports on other modules(A-10C, FC Aircraft) and other values on the F-16C module properly export/import.

**Comment by WarLord211** [comment]
fixuploaded in maser branch

**Comment by WarLord211** [comment]
latest release work ok?

**Comment by wiggles5289** [comment]
Yup! Working now
