### ISSUE TITLE
UH-1H Wiper Speed lacking set_state input interface

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#45]
`UH-1H/WIPER_SPD` currently only offers `fixed_step` adjustment and not `set_state`. Is this something that can be added, or is it up to the module to implement?

**Comment by WarLord211** [comment]
i look into this

**Comment by WarLord211** [comment]
currently not changeable. i got no switch to work exept the existing one.
it was planed/or is planed as multipost switch but atm i cant change it without braking the function

**Comment by charliefoxtwo** [comment]
That's unfortunate. If there's nothing you can do, I'm ok with closing the issue - up to you.
