### ISSUE TITLE
json files are only generated in developer mode

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#48]
This means that anybody cloning the master branch will need to manually modify biosdevmode in order to get the json files to regenerate.

I'd suggest either modifying the default behavior or documenting this feature; it stumped me for a few minutes.

**Comment by WarLord211** [comment]
my mistake. its changed back.
its documented here:
https://github.com/DCSFlightpanels/DCSFlightpanels/wiki/DCS-BIOS-Tuning

**Comment by charliefoxtwo** [comment]
Ah, my apologies, you're right it is documented. Thanks!
