### ISSUE TITLE
Receiving F-14B bios data when in A-10C II

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#51]
I'm really not sure how this happened, but even though I'm in an A-10C, dcs-bios is _also_ sending data for the F-14B. This is in a fresh launch of the game where I haven't flown the F-14B yet.

![image](https://user-images.githubusercontent.com/30303272/120141636-b4a40980-c191-11eb-9048-a13e6f94a578.png)
![image](https://user-images.githubusercontent.com/30303272/120141671-c1c0f880-c191-11eb-9ea3-2442914889a5.png)
![image](https://user-images.githubusercontent.com/30303272/120141691-cbe2f700-c191-11eb-8957-018155744b48.png)

**Comment by WarLord211** [comment]
Thats more or les normal if you load all luas. the Data would send to all of them.
If matching Argument are there, you get data.

for cockpit building ist recomended to pick your needed luas.

https://github.com/DCSFlightpanels/DCSFlightpanels/wiki/DCS-BIOS-Tuning

**Comment by charliefoxtwo** [comment]
I see.

I'm not really building a cockpit - I've written a [utility](https://github.com/charliefoxtwo/ViLA) to change the LEDs on my Virpil devices depending on the output of DCS-BIOS. It's not really a specific cockpit, since I use the same hardware for various aircraft and want certain things to light up differently.

I guess the solution is just going to be allowing for enabling/disabling configurations on my end.

**Comment by WarLord211** [comment]
would be the best
