### ISSUE TITLE
C-101 - Three position switches behaving as two position switches

### ISSUE THREAD

**Issue by Ettenmure** [DCSFlightpanels/dcs-bios#52]
The ignition and seat height switches on both the front and rear cockpit of the C-101 are three position switches, where the central position is OFF, but in DCS-BIOS they behave as two position switches making impossible two access all three positions.
On the control reference page they only have one pin but they should have two.

This means that on the seat height switch is only possible to select the "up" or "down" positions not the "off", so the seat is constantly going up or down and can’t be stopped at a middle position. Same with the ignition switch, the “off” position can’t be selected.

The non-working switches are:

FRONT_CONT_ING_START
BACK_CONT_ING_START
FRONT_SEAT_HEIGHT
BACK_SEAT_HEIGHT

**Comment by WarLord211** [comment]
fix uploaded.
pls try again

**Comment by Ettenmure** [comment]
That fix didn’t work, I have made a pull request witch changes that make the switches behave as expected.

#53
