### ISSUE TITLE
A-10C II Toggle Steerpoint not functioning

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#54]
This is a weird one (and potentially a module bug?) - the A-10C II "Toggle Steerpoint" `AAP_STEER` control does not seem to _functionally_ work. What's weird is that changing the value in dcs-bios works, and you can see the switch move in game, and dcs-bios shows the value of the switch in game - but the switch doesn't do the thing it's supposed to do when you use dcs-bios.

Example:
1. Load into A-10C II Takeoff Instant Action
2. Look at AAP and left/right-click the steerpoint switch. Then look at the HUD and notice the active steerpoint has changed.
3. Now do the same with dcs-bios. Notice that while the switch moves, the active steerpoint doesn't actually change.

**Comment by WarLord211** [comment]
double check everything.
must be module/DCS side

**Comment by talbotmcinnis** [comment]
A while back ED introduced an issue with the cdu steer switch where it was double clicking on each activation.  At that point I switched my bindings to the ufc steer switch and haven't looked back.  Not ideal, but there may still be issues with the ed cdu and so consider that as a workaround.

**Comment by charliefoxtwo** [comment]
Good to know... That's a clever workaround. I've double-checked everything so many times. What's weird is that clicking the switch in game still works, but even though bios moves the switch in game it doesn't. Quite odd.
