### ISSUE TITLE
AJS-37 Viggen missing status lights

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#56]
I noticed the following status lights are missing from the Viggen:
 - AFK enabled light (**not** the AFK warning light on the caution panel)
 - AFK 15deg aoa light
 - falld last light (no stores remaining)
 - transsonic flight light
 - afterburner stages 1-3 lights

**Comment by WarLord211** [comment]
i check. have you maybe screens to find them? i dont know the plane well

**Comment by charliefoxtwo** [comment]
I'll get some pictures for you, but it might take me a day to get to it :) 

The AFK lights are on the top left of the dash next to the green SAS/autopilot lights. The falld last and transsonic lights are on the top right of the dash in a similar position. The afterburner lights are on the bottom middle-right of the dash - you should the the numbers 1, 2, 3, and the light up as you apply more power to the engine.

**Comment by WarLord211** [comment]
ok that should be enough to find it with chucks guides :)

**Comment by WarLord211** [comment]
these are in the latest version:

defineIndicatorLight("FALLD_LAST_LAMP", 461, "Front Panel Lights", "Falld Last (Stores Released) Lamp (red)")
defineIndicatorLight("REV_TRANSONIC_LAMP", 462, "Front Panel Lights", "Revadvr Transonic Lamp (red)")

**Comment by WarLord211** [comment]
a quickie before breakfast.
found some more. uploaded but no json generated

**Comment by charliefoxtwo** [comment]
Oh awesome! Sorry I completely forgot to check the latest version. Thanks for adding those! I'll try to test today.

**Comment by charliefoxtwo** [comment]
My tests:
 - [x] `AFK_ENABLED_L` spelling error in description
 - [ ] `ALT_WARNING_LAMP`
 - [x] `AOA_15_L`
 - [x] `BURNER_STAGEx_L` **needs fix** (currently only one is lit at a time, however they should stay lit - if you are in zone 3 AB, then lights 1, 2, and 3 should all be lit)
 - [ ] `FALLD_LAST_LAMP`
 - [x] `HUVUDVARNING_x`
 - [x] `RDR_xx_L`
 - [x] `REVERSAL_L`
 - [x] `REV_TRANSONIC_LAMP`

**Comment by WarLord211** [comment]
Burnerstage and typo fix is UP
