### ISSUE TITLE
MiG-19P Duplicate EMERG_GEAR key

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#57]
`EMERG_GEAR` is present in two places. I'm not familiar with this aircraft as I don't own it, but looks like just a naming collision.

https://github.com/DCSFlightpanels/dcs-bios/blob/281f8d8116f99082ee94301c7c3539757b1cdd66/Scripts/DCS-BIOS/lib/MiG-19P.lua#L210
https://github.com/DCSFlightpanels/dcs-bios/blob/281f8d8116f99082ee94301c7c3539757b1cdd66/Scripts/DCS-BIOS/lib/MiG-19P.lua#L355

**Comment by WarLord211** [comment]
good find

**Comment by charliefoxtwo** [comment]
Looks good to me now, thanks!
