### ISSUE TITLE
F-16 EHSI CRS Set Knob function only goes up and not down

### ISSUE THREAD

**Issue by wiggles5289** [DCSFlightpanels/dcs-bios#61]
F-16C Module using DCS OB and DCSFP V07.40

In the browser plugin and with hardware(used encoder, works fine), the EHSI CRS Set Knob only increases with an input.

Go to browser plugin and try changing the CRS Set Knob with INC and DEC and you will see the issue.

I will see if other F-16 encoders are borked and report back if I actually do work to find issues.

**Comment by wiggles5289** [comment]
The issue is kinda fixed. Toggling the CRS Set Button allowed it to work. Not sure if it caused the issue. Will reopen if it occurs again.

**Comment by WarLord211** [comment]
you are right was false defined. is now a rotary. fix uploaded into FP BIOS Master branch
