### ISSUE TITLE
M2000-C uhf/vhf/vor preset error from 1 unit

### ISSUE THREAD

**Issue by shan-aya** [DCSFlightpanels/dcs-bios#63]
hi,
on radio panel , uhf , vhf & vor knob show selection with error

uhf : 1 on DCS , 0 on saitek ( -1 and 0 exist )
vhf : 2 on DCS , 1 on saitek (-1 )
vor : 108.3 on DCS , 109.3 on saitek (-1 )

**Comment by WarLord211** [comment]
does it work in live preview of DCS BIOS?

**Comment by shan-aya** [comment]
in live preview M-2000C/UHF_PRESET_KNOB 
 knob uhf : integer = 19, string = 19 
but in dcs knob show = 20

**Comment by shan-aya** [comment]
and uhf is "infinite" knob, vhf is "blocked 2-20" knob

**Comment by WarLord211** [comment]
it comes on my todo list

**Comment by shan-aya** [comment]
ok,
how i can help you ?

**Comment by WarLord211** [comment]
test my new version when i have uploaded it ;)

**Comment by WarLord211** [comment]
uploaded to master branch. pls test it.-
start a flight before testing with Flightpanels or arduino to rewrite the json files

**Comment by shan-aya** [comment]
ok 
VHF --> infinite knob now 👍 
        ---> no change on value : ch20 in saitek, 19 in integer, 001 in string, 1 in DCS

**Comment by WarLord211** [comment]
control panel works i assume.

saitek has to be changed too, but i cant do this.
best would bet to make anissue in FP program about fase view in the M2000

**Comment by shan-aya** [comment]
it's good that output integer is less -2 than outpout string ( wich is right with dcs  cockpit value ) ? 
you think that is FP issue ?

so is same thing with UHF and VOR ?

**Comment by shan-aya** [comment]
UHF range is 0-19 not 1-20

**Comment by WarLord211** [comment]
there is a 20 in cockpit

**Comment by shan-aya** [comment]
UHF range is 0-19 in saitek 
0-19 in output integer
 1-20 in output string

**Comment by WarLord211** [comment]
here i mean only BIOS side = Cockpit - live preview/Control referensce app.

0-19 interger = 20 need for conversion in adrduino/Saitek
1-20 string = converted for displays

if OK pls close issue

**Comment by shan-aya** [comment]
thx for info ig go working on dcsfp ;)
