### ISSUE TITLE
m2000c not accurate speed dcs-bios / dcs m2000c HUD-VTH

### ISSUE THREAD

**Issue by shan-aya** [DCSFlightpanels/dcs-bios#65]
hi,
speed return from dcs-bios is different from HUD SPEED in dcs
same thing with MACH which is really really different ...

**Comment by WarLord211** [comment]
need more info! wich readouts do you mean

**Comment by shan-aya** [comment]
no i try convert but is wrong or it's me :) ..
in HUD , unit is KTH for speed
if i read bios, speed needle is 34124 for 521 kth ... no right conversion possible
mach is 6150 for 0.94 .. same thing

**Comment by shan-aya** [comment]
commonData is more accuracy but not perfect
airspeed KNT is 510 for 521 in hud if it help :(

**Comment by WarLord211** [comment]
i look what i can find.
 M2000 is old code and not writen by me. i only try to hold it up2date. have to digg in.

**Comment by WarLord211** [comment]
i checked the speed readouts. this is what i get from the plane. thes will need an convertion. 
but idk which i can oly readout what the plane gives me

**Comment by shan-aya** [comment]
oki wich isd units from bios ? 
M-2000C/SPEED_KTS_NEED
M-2000C/SPEED_MACH
to find formula to convert

**Comment by shan-aya** [comment]
ok,
i find with slope formula
[M-2000C/SPEED_KTS_NEED * 0,01526] to give correct speed in dcsfp
