### ISSUE TITLE
BF-109 K-4 bugs

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#67]
Just stumbled across these. I don't fly the module too much but another user of my software that uses DCS-BIOS noticed some issues.

1. `/METHANOL_WATER _PRES_VALUE` has a space in the middle of it
2. I'm not sure what's going on here, but `IGN_ON` doesn't seem to work (and `BAT_ON`, and potentially others)
![image](https://user-images.githubusercontent.com/30303272/131261079-9e73e6ab-48b9-4fec-91c4-db3026b66f1f.png)
![image](https://user-images.githubusercontent.com/30303272/131261101-ad2b67c6-e745-4027-8caf-a5d40c214fed.png)

**Comment by WarLord211** [comment]
these for when the fuse is out, to put it back in (as far as i find out trough testing) why its NAN i dont know.

space typo is fixed but not uploaded yet

**Comment by charliefoxtwo** [comment]
Yup the purpose of the controls definitely makes sense to me, but it seems to always be 0 so I think something funky is going on.

**Comment by WarLord211** [comment]
fix is inbound
