### ISSUE TITLE
VNAO T-45 Duplicate key `BATTERY1_SW`

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#68]
Seems to be a simple copy-paste error, I believe this is the problematic line https://github.com/DCSFlightpanels/dcs-bios/blob/f2b9f8e88343f1cda02860e28ede65da435e791e/Scripts/DCS-BIOS/lib/VNAO_T-45.lua#L34

**Comment by WarLord211** [comment]
fixed

**Comment by charliefoxtwo** [comment]
looks good on my end now, thanks!
