### ISSUE TITLE
Control name errors

### ISSUE THREAD

**Issue by charliefoxtwo** [DCSFlightpanels/dcs-bios#69]
Just improved some logging on my end and found a few more problem names... they all have whitespace where they shouldn't. This should be all of them!

https://github.com/DCSFlightpanels/dcs-bios/blob/fdeebac9429e951b831128426fe7d40cf1dc18f7/Scripts/DCS-BIOS/lib/A-4E-C.lua#L267
https://github.com/DCSFlightpanels/dcs-bios/blob/fdeebac9429e951b831128426fe7d40cf1dc18f7/Scripts/DCS-BIOS/lib/Mi-24P.lua#L642
https://github.com/DCSFlightpanels/dcs-bios/blob/fdeebac9429e951b831128426fe7d40cf1dc18f7/Scripts/DCS-BIOS/lib/VNAO_T-45.lua#L243

**Comment by WarLord211** [comment]
fixed
