### ISSUE TITLE
F-5E error accelerometer 

### ISSUE THREAD

**Issue by ALBLANCOD** [DCSFlightpanels/dcs-bios#70]
It is not reading the acceleration values ​​correctly, in previous versions it worked correctly. Thank you.

**Comment by WarLord211** [comment]
need some more infos.

1. name of the item
2.what does not work?

**Comment by ALBLANCOD** [comment]
dcs-bios in the F-5 module, the acceleration export settings do not
work. I have the latest version of the F-5 plugin installed. Thans.

**Comment by WarLord211** [comment]
Plugin? 
you use HUB?!

**Comment by ALBLANCOD** [comment]
dcs-bios allows you to export values ​​that can be read with arduino
and perform different actions. From the dcs-bios of the F-5 Tiger, I
read the acceleration data, (G-forces) and and act on mechanical
devices.

**Comment by WarLord211** [comment]
yes i know that.
which Valves dou you read. (Name of the readout you use in arduino code)
Which version of BIOS do you use ( HUB, FP Fork Master/Release)
you wrote it worked before, which version?

without these infos i cant search for the problem

**Comment by ALBLANCOD** [comment]
I am preparing the documentation to explain myself better.

**Comment by ALBLANCOD** [comment]
[image: image.png]


[image: Screen_210923_010306.png]

With DCS Word active and the F-5 flying, the acceleration values are
displayed correctly on the indicator, but the DCS-BIOS readings are
incorrect.
These parameters     previously worked correctly.

I hope I have explained myself correctly.

Thans.

**Comment by WarLord211** [comment]
pics are not showing.

Which version of BIOS do you use ( HUB, FP Fork Master/Release)
you wrote it worked before, which version?

**Comment by ALBLANCOD** [comment]
It may be that the error occurred with the DCS WORLD update and is not
a DCS-BIOS problem. Thank you.

**Comment by WarLord211** [comment]
i found some strange valves.
Uploaded a fix to flightpanel Master branch

**Comment by ALBLANCOD** [comment]
Thank you very much Sven. Problem solved, the solution provided works correctly.
Very good work.
Receive a cordial greeting from Spain.
