### ISSUE TITLE
Help processing UDP datagrams

### ISSUE THREAD

**Issue by gmarquezalvzrez** [DCSFlightpanels/dcs-bios#81]
Hi there!

I'm developing a plugin for Touch Portal and need to process the data stream coming form DCS-BIOS to create the correct messages  to be sended to TP.
But there is something I'm missing when I read the  Developer Guide, because if I try to process the data manually, usin pen, paper and calculator, I can't find the correlation between the information received and charts of data available in the airplane json file, the CommonData, the MetaDataStart and the MetaDataEnd json files.

Here you can see the a couple of datagrams sorted in 16 bits words;

00-14------------20
00-02------------2
20-20------------8224
04-4A------------1098
00-04------------4
00-0F------------15
03-C8------------968
74-A0------------29856
00-02------------2
A0-20------------40992
STREAM END
00-16------------22
00-02------------2
20-20------------8224
04-00------------1024
00-04------------4
2E-30------------11824
2E-37------------11831
04-4C------------1100
00-02------------2
03-CC------------972
74-A0------------29856
00-02------------2
STREAM END

The left side are  bytes pairs in big endian to match with the address showed in the Advanced view of the DCS.BIOS Web console.
The right side are just those 2 bytes converted in ushort numeric type.
I know that only the addresses would follow this simple conversion, but looking at the json files (F18, CommonData, MetaDataStart and MetaDataEnd) I can't find any of those ushort numbers as a valid address in the named files.

Ok, to be precise I could found one:  74-A0 is the Hook Lever and 00-02, if I undo the non-Little endian operation, is the mask to be applied.

But that is the only address I could find, so I know that I'm missin something very simple but very important and after several hour of test and fail I can't find what is it.

You could argue that not all the data exported fits in 16 bits, string data for example, yes I know it.
But the very first 16 bits of each datagram are the begining of the packet, just without the four 0x55 characters which mark the start of a new packet, and I can't fing any address correponding with the bytes 0x0014.
Then I can't start to process the information of the packet because I don't know what mask or shift need to be applied.

Could you help me to understand what I'm missing?
Thank you very much and sorry for the long post.
Cheers!

**Comment by talbotmcinnis** [comment]
I don’t know the specifics and did not write the core of this, but this project contains a python library which receives dcs-bios streams, so maybe digging into it you will find the details you need.

https://github.com/talbotmcinnis/TabletCDU

**Comment by gmarquezalvzrez** [comment]
Thank you Talbot.

I see that you process the bytes one by one, and just after discard the 4 bytes header, you star to accumulate the less significative and the more significative pair of bytes of an address.

In the two data packets I posted before, if I pick the first pair of bytes (i.e.: 00-14 ) and I open the json files where the hole list of address of the airplane is exposed, I can't find the address 0x0014, 20 in decimal.

So now this is my mayor doubt, because I can't find the match between the address readed and the address in the json files and I dont know if I'm doing something wrong or I'm missing something.
