### ISSUE TITLE
Possible to add Hotas commands?

### ISSUE THREAD

**Issue by jonsky7** [DCSFlightpanels/dcs-bios#82]
Hi

I'd like to be able to use DCS-BIOS to send the odd HOTAS command, particularly at the moment I'd like to send commands for the Dogfight/Missile override switch in the F16.

Possible at all?

Thanks

**Comment by WarLord211** [comment]
Only possible via dcs-bios when clickable in cockpit. For f-16  I know they are not.
Via flightpanel software I suggest do it via key command
