### ISSUE TITLE
Multi plane with same buffer name 

### ISSUE THREAD

**Issue by Jack-XHP** [DCSFlightpanels/dcs-bios#85]
I am working on a control box using dcs bios for OLED and led output. Currently, I make the box automatically switch its display given different planes. However, I have encountered serval cases where two planes' buffer names are the same, which results in displaying only one of the plane's content for that buffer.  I tried to rename the buffer name, but seems like that will cause it bot be updated during DcsBios:loop();.

I am wondering if there is a way in Arduino code to fix that problem or I have to modify each plane's plugin to solve that problem?

**Comment by WarLord211** [comment]
Maybe:

https://flyandwire.com/2019/09/24/dcs-bios-multiple-modules-at-the-same-time/
or
https://forums.eagle.ru/topic/197601-dcs-bios-dynamic-mapping-based-on-aircraft-type-code/

**Comment by WarLord211** [comment]
the name come from the plane luas. but not changeable, because this would break all programmed cockpits of the users if they update BIOS.

**Comment by Jack-XHP** [comment]
if it is not possible to rename it, is there a way to dynamically update the parameter of the buffer? ie address and offset?

**Comment by WarLord211** [comment]
they is generated by BIOS automatic from the lua when an flight is started -Json File.
it depends on the position in the lua. But again changing breaks existing cockpits

may anyone on your discord hab an method?! (link in readme)
