### ISSUE TITLE
F-16 RPM (tach) Gauge Values

### ISSUE THREAD

**Issue by mg102279** [DCSFlightpanels/dcs-bios#86]
Thanks for your support in DCS-BIOS and keeping it alive.
I have an issue. My wife and I are trying to drive an x27 stepper motor but, she needs the values of the RPM (tachometer) gauge for the F-16 so she can help me get it working.  How can we see what values are being sent communicating between DCS and DCS-BIOS? 

Thanks.
Matt

**Comment by WarLord211** [comment]
you mean a list of readouts?

vie the Chrome App you can see them or open the Control Ref.html in docs folder

**Comment by mg102279** [comment]
I mean the live data for just the RPM gauge itself for reference so we can know what we are needing to make the RPM gauge work correctly.

**Comment by mg102279** [comment]
I don't know if you saw my comment on discord. I found some code. Just need to tweak it!
