### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by mg102279** [DCSFlightpanels/dcs-bios#87]
So here is the BIG issue. I have a network infrastructure in my house. Due to the security vulnerabilities in Google Chrome, I can't use it. How am I supposed to use this when I can't use chrome. I am sure there are others out there that don't like to use chrome either for different reasons. The browser page seemed to do better for everyone for compatibility.  Can you assist with this? I do need live data but, it will only work in chrome.

**Comment by WarLord211** [comment]
its a App thats written in Chrome API.
Changing that is far away from my Programming knowlege 
sorry
