### ISSUE TITLE
support for ATmega32u4 arduinos?

### ISSUE THREAD

**Issue by ninchistudios** [DCSFlightpanels/dcs-bios#90]
Hey, I am currently designing some PCBs for an open source Apache TEDAC, and would like to use a ATmega32u4 based Arduino in the design. The original dcs-bios documentation specifies "DCS-BIOS supports boards that feature the ATMega328 or the ATMega2560 microcontrollers". Is that the case with this fork?  Can ATmega32u4 Leonardos/Pro Micros be used successfully?

In either case, it would be useful if the docs at https://github.com/DCSFlightpanels/dcs-bios/blob/master/README.adoc were specific about the hardware requirements. Thanks heaps!

**Comment by KPCKxd** [comment]
I had only luck with arduino uno/nano. It should support mega aswell. Tried teensy 4.1, that worked aswell, but was kind pain to get running.

**Comment by talbotmcinnis** [comment]
Also fyi, you linked to the pc side of dcs-bios which is hardware independent. The arduino side is here:  https://github.com/DCSFlightpanels/dcs-bios-arduino-library/wiki

**Comment by ninchistudios** [comment]
thanks lads

**Comment by Maverick87Shaka** [comment]
> I had only luck with arduino uno/nano. It should support mega aswell. Tried teensy 4.1, that worked aswell, but was kind pain to get running.

What was the pain in using teensy? I'm considering this board to use integrated USB HOST HUB but if there is some limitation, I'll skipp and continue the work with mega ;)

Thanks @KPCKxd

**Comment by talbotmcinnis** [comment]
Thats 100% true and documented as such.  Don’t most boards have limited irq enabled pins anyway?
My initial assessment was “I’m handling data that has travelled through lua, then a udp stack, then a serial port, so microseconds of additional delay are irrelevant”.  I use default serial for everything.  But I do encounter many who get very excited about irq mode.  I’m curious if you have any evidence of measurable performance impact from default mode?
