### ISSUE TITLE
The A10C's" CDU Display"conflicts with the F14‘s "Display ".

### ISSUE THREAD

**Issue by bird5312** [DCSFlightpanels/dcs-bios#91]
The A10C "CDU Display "(Category Filter) codes cannot work with  F14‘s "Display"(Category Filter) codes. F14‘s Display codes may lead to CDU's characters not fully display.
There are parts of code that cannot be used at the same time:
          A10C:DcsBios::StringBuffer<24> cduLine4Buffer(0x1220, onCduLine4Change);
          F14:DcsBios::IntegerBuffer pltHudPwSwBuffer(0x1222, 0x0001, 0, onPltHudPwSwChange);
                 DcsBios::IntegerBuffer pltHsdPwSwBuffer(0x1222, 0x0002, 1, onPltHsdPwSwChange);
                 DcsBios::IntegerBuffer pltHsdEcmOverBuffer(0x1222, 0x0200, 9, onPltHsdEcmOverChange);
                 DcsBios::IntegerBuffer pltHsdDisModeBuffer(0x1222, 0x0180, 7, onPltHsdDisModeChange).
The possible cause is that the data start address of the two models is not properly selected.
The lua code:"BIOS.protocol.beginModule("A-10C", 0x1000)"and"BIOS.protocol.beginModule("F-14B", 0x1200)".

**Comment by WarLord211** [comment]
maybe. and why the needed export for the same time?

**Comment by bird5312** [comment]
您好：
      您发给我的信件已经收到。

**Comment by bird5312** [comment]
> maybe. and why the needed export for the same time?

https://www.bilibili.com/video/BV1i44y157SG?from=search&seid=10860133654613626073&spm_id_from=333.337.0.0

**Comment by WarLord211** [comment]
?
you can fligh only one plane, so i see not a problem?! It exists several programms that uses more than one plane.
